//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerModel.SqlAccess.EmployeeSetup.TrainingSetup {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServerModel.SqlAccess.EmployeeSetup.TrainingSetup.Sql", typeof(Sql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ////*
        ///--GetEmployeeTrainingsByCompId.Sql
        ///
        ///--select * from EMP_Training
        ///
        ///DECLARE @CompId uniqueidentifier = &apos;00000000-0000-0000-0000-000000000000&apos;;
        ///
        ///*/
        ///
        ///SELECT 
        ///	 empTraining.Id
        ///	,empTraining.FormDate
        ///	,empTraining.CompId
        ///	,empTraining.EMP_Info_Id
        ///	,emp.FullName AS &apos;EmployeeName&apos;
        ///	,empTraining.TrainingHead_EMP_Id
        ///	,empTrainingHead.FullName AS &apos;TrainingHeadEmployeeName&apos;
        ///	,empTraining.MS_Training_Id
        ///	,training.TrainingName
        ///	,empTraining.StartOn
        ///	,empTraining.EndOn
        ///	,empTraining.Status
        ///	, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetEmployeeTrainingsByCompId {
            get {
                return ResourceManager.GetString("GetEmployeeTrainingsByCompId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ////*
        ///--UpsertEmployeeTraining.Sql
        ///
        ///--select * from EMP_Training
        ///
        ///DECLARE @Id uniqueidentifier = &apos;00000000-0000-0000-0000-000000000000&apos;;
        ///DECLARE @CompId uniqueidentifier = &apos;00000000-0000-0000-0000-000000000000&apos;;
        ///DECLARE @EMP_Info_Id uniqueidentifier = &apos;00000000-0000-0000-0000-000000000000&apos;;
        ///DECLARE @TrainingHead_EMP_Id uniqueidentifier = &apos;00000000-0000-0000-0000-000000000000&apos;;
        ///DECLARE @MS_Training_Id INT = 0;
        ///DECLARE @StartOn datetime2 = GETDATE();
        ///DECLARE @EndOn datetime2;
        ///DECLARE @Status INT  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpsertEmployeeTraining {
            get {
                return ResourceManager.GetString("UpsertEmployeeTraining", resourceCulture);
            }
        }
    }
}
