//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerModel.SqlAccess.EmployeeSetup.AddressesInfo {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlEmpAddresses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlEmpAddresses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServerModel.SqlAccess.EmployeeSetup.AddressesInfo.SqlEmpAddresses", typeof(SqlEmpAddresses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///--- GetEmployeeAddressByAddressId.sql.Sql
        ////*
        ///DECLARE @empDocId UNIQUEIDENTIFIER = &apos;3D360BA8-2B12-4DB7-BAC9-9ADFD3553E1E&apos;
        ///
        ///*/
        ///
        ///
        ///SELECT [Id]
        ///      ,[FormDate]
        ///      ,[MachineId]
        ///      ,[MachineIp]
        ///      ,[CompId]
        ///      ,[EMP_Info_Id]
        ///      ,[AddressTypeId]
        ///      ,[AddressLine1]
        ///      ,[AddressLine2]
        ///      ,[FlatNo]
        ///      ,[Premise]
        ///      ,[Road]
        ///      ,[Area]
        ///      ,[Town]
        ///      ,[MS_State_Id]
        ///      ,[MS_Country_Id]
        ///      ,[PinCode]
        ///      ,[FullAddress]
        ///      ,[AddressProofDoc]        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetEmployeeAddressByAddressId {
            get {
                return ResourceManager.GetString("GetEmployeeAddressByAddressId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --DECLARE @json NVARCHAR(MAX) = 
        ///--&apos;[
        ///--    {
        ///--        &quot;Id&quot;: &quot;00000000-0000-0000-0000-000000000000&quot;,
        ///--        &quot;FormDate&quot;: &quot;2025-08-14&quot;,
        ///--        &quot;MachineId&quot;: 101,
        ///--        &quot;MachineIp&quot;: &quot;192.168.1.10&quot;,
        ///--        &quot;CompId&quot;: &quot;00000000-0000-0000-0000-000000000000&quot;,
        ///--        &quot;EMP_Info_Id&quot;: &quot;00000000-0000-0000-0000-000000000000&quot;,
        ///--        &quot;AddressTypeId&quot;: 1,
        ///--        &quot;AddressLine1&quot;: &quot;Addr1&quot;,
        ///--        &quot;AddressLine2&quot;: &quot;Addr2&quot;,
        ///--        &quot;FlatNo&quot;: &quot;A-101&quot;,
        ///--        &quot;Premise&quot;: &quot;Premise1&quot;,
        ///--     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpsertEmployeeAddresses {
            get {
                return ResourceManager.GetString("UpsertEmployeeAddresses", resourceCulture);
            }
        }
    }
}
