//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerModel.SqlAccess.Punch {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PunchSql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PunchSql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServerModel.SqlAccess.Punch.PunchSql", typeof(PunchSql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///--AddPunchInOut
        ///
        ///
        ///--DECLARE @machineId nvarchar(50) = &apos;&apos;
        ///--DECLARE @machineIp nvarchar(50) = &apos;&apos;
        ///--DECLARE @compId UNIQUEIDENTIFIER = &apos;00000000-0000-0000-0000-000000000000&apos;
        ///--DECLARE @createdBy UNIQUEIDENTIFIER = &apos;00000000-0000-0000-0000-000000000000&apos;
        ///--DECLARE @date DATE = CAST(GETDATE() AS date)
        ///--DECLARE @branchId INT = 1
        ///--DECLARE @empId UNIQUEIDENTIFIER = &apos;00000000-0000-0000-0000-000000000000&apos;
        ///--DECLARE @inTime TIME(7) = &apos;09:30:00.000&apos;
        ///--DECLARE @outTime TIME(7) = &apos;18:30:00.000&apos;
        ///
        ///
        ///
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddPunchInOut {
            get {
                return ResourceManager.GetString("AddPunchInOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---- Sql.GetEmployeesPunchesByComIdAndShiftId
        ///
        ////*
        ///DECLARE @compId UNIQUEIDENTIFIER = &apos;00000000-0000-0000-0000-000000000000&apos;
        ///DECLARE @shiftId INT = 4005
        ///DECLARE @filterDate DATE = &apos;2025-09-01&apos;  -- Pass the date to filter by month &amp; year
        ///
        ///*/
        ///
        ///;WITH PunchesRanked AS (
        ///    SELECT
        ///        attd.EMP_Info_Id,
        ///        attd.punchDate,
        ///        attd.punchTime,
        ///        ROW_NUMBER() OVER (PARTITION BY attd.EMP_Info_Id, attd.punchDate ORDER BY attd.punchTime ASC) AS rank_in,
        ///        ROW_NUMBER() OVER (PARTI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetEmployeesPunchesByComIdAndShiftId {
            get {
                return ResourceManager.GetString("GetEmployeesPunchesByComIdAndShiftId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///--GetPresentEmpByBranch
        ///
        ///--DECLARE @attendaceDate DATE = GETDATE()
        ///--DECLARE @branchId INT = 1
        ///
        ///SELECT 
        ///		 attd.EMP_Info_Id
        ///		,emp.FullName
        ///		,desg.DesignationName
        ///		,branch.BranchName
        ///		,shiftMS.ShiftName
        ///		,attd.Date AS AttendanceDate
        ///		,MIN(attd.Intime) AS PunchIn
        ///		,MAX(attd.Outtime) AS PunchOut 
        ///	FROM EMP_Punch AS attd 
        ///		INNER JOIN EMP_Info AS emp ON emp.Id = attd.EMP_Info_Id
        ///		INNER JOIN MS_Designation AS desg ON desg.Id = emp.MS_Designation_Id
        ///		INNER JOIN MS_Branch AS branch ON b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetPresentEmpByBranch {
            get {
                return ResourceManager.GetString("GetPresentEmpByBranch", resourceCulture);
            }
        }
    }
}
