//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerModel.SqlAccess.PMS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PMSSqls {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PMSSqls() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServerModel.SqlAccess.PMS.PMSSqls", typeof(PMSSqls).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///--select * from PMS_PerformanceCheckIns
        ///--select * from PMS_EmployeeGoals
        ///
        ///--DECLARE @CompId UNIQUEIDENTIFIER = &apos;D33691FC-7EB9-4D1C-888C-4F4B6E204680&apos;;
        ///--DECLARE @EmpId UNIQUEIDENTIFIER = &apos;EA186978-58F9-4153-9863-DCD4E7AF4F18&apos;;
        ///
        ///SELECT 
        ///		 empPerfCheckIns.CheckInId
        ///		,empGoalId.EMP_Info_Id
        ///		,empGoalId.GoalTitle
        ///		,empGoalId.GoalDescription
        ///		,empGoalId.Weightage
        ///		,empGoalId.TargetValue
        ///		,empPerfCheckIns.ProgressPercentage
        ///		,empPerfCheckIns.Comments
        ///  FROM PMS_PerformanceCheckIns AS em [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetEmpGoalProgressByEmpId {
            get {
                return ResourceManager.GetString("GetEmpGoalProgressByEmpId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///--Sql.GetEmpGoalProgressByGoalId
        ///
        ////**
        ///
        ///DECLARE @CompId UNIQUEIDENTIFIER = &apos;C225A53F-9ECB-4B9A-88DC-EAEF6115C2A4&apos;;
        ///DECLARE @goalId INT = 1010;
        ///
        ///**/
        ///
        ///
        ///SELECT DISTINCT
        ///		 empPerfCheckIns.FormDate
        ///		,empGoal.MS_PerformanceCycles_Id
        ///		,cycle.CycleName
        ///		,empGoal.GoalTitle
        ///		,empGoal.MS_GoalCategories_CategoryId
        ///		,goalCat.CategoryName
        ///		,empPerfCheckIns.ProgressPercentage
        ///		,empPerfCheckIns.Comments
        ///		,empGoalId.EMP_Info_Id
        ///        ,emp.FullName AS &apos;EmployeeName&apos;
        ///FROM PMS_PerformanceCheckI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetEmpGoalProgressByGoalId {
            get {
                return ResourceManager.GetString("GetEmpGoalProgressByGoalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///--Sql.GetEmpGoalsApprovalStatusByCycleId
        ///
        ////**
        ///
        ///DECLARE @cycleId INT = 3;
        ///DECLARE @compId UNIQUEIDENTIFIER = &apos;C225A53F-9ECB-4B9A-88DC-EAEF6115C2A4&apos;
        ///
        ///**/
        ///
        ///select 
        ///		 empGoal.GoalId AS &apos;PMS_EmployeeGoals_GoalId&apos;
        ///		,empGoal.FormDate
        ///		,empGoal.CompId
        ///		,empGoal.EMP_Info_Id
        ///		,emp.FullName AS &apos;EmployeeName&apos;
        ///		,empGoal.MS_PerformanceCycles_Id
        ///		,pmsCycle.CycleName
        ///		,empGoal.MS_GoalCategories_CategoryId
        ///		,goalCat.CategoryName
        ///		,empGoal.GoalTitle
        ///		,empGoal.Status
        ///		,goalApproval.ApproverI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetEmpGoalsApprovalStatusByCycleId {
            get {
                return ResourceManager.GetString("GetEmpGoalsApprovalStatusByCycleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ////*
        ///DECLARE @EmpId UNIQUEIDENTIFIER = &apos;5DE2FE64-4D6B-4E75-BA75-B43A143BC4BD&apos;;
        ///DECLARE @cycleId INT = 3;
        ///*/
        ///
        /// SET NOCOUNT ON;
        ///
        ///    SELECT DISTINCT
        ///         empGoal.GoalId
        ///        ,empGoal.FormDate
        ///        ,empGoal.MachineId
        ///        ,empGoal.MachineIp
        ///        ,empGoal.CompId
        ///        ,empGoal.EMP_Info_Id
        ///		,emp.FullName
        ///		,empGoal.MS_PerformanceCycles_Id
        ///		,pmsCycle.CycleName
        ///		,empGoal.MS_GoalCategories_CategoryId
        ///		,goalCat.CategoryName
        ///		,empGoal.GoalTitle
        ///		,empGoal.GoalDescription
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetEmployeeGoalsByEmpId {
            get {
                return ResourceManager.GetString("GetEmployeeGoalsByEmpId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///--Sql.GetEmployeesByCycleIdAndStatus
        ///
        ////**
        ///DECLARE @cycleId int = 3;
        ///DECLARE @status NVARCHAR(50) = &apos;Approved&apos;
        ///**/
        ///
        ///
        ///select distinct empGoal.EMP_Info_Id, emp.FullName
        ///	from PMS_GoalApprovals AS goalAppr
        ///		inner join PMS_EmployeeGoals AS empGoal ON empGoal.GoalId = goalAppr.PMS_EmployeeGoals_GoalId
        ///		inner join EMP_Info AS emp ON emp.Id = empGoal.EMP_Info_Id
        ///	where goalAppr.ApprovalStatus = @status
        ///		and goalAppr.MS_PerformanceCycles_Id = @cycleId.
        /// </summary>
        internal static string GetEmployeesByCycleIdAndStatus {
            get {
                return ResourceManager.GetString("GetEmployeesByCycleIdAndStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///--DECLARE @CompId UNIQUEIDENTIFIER = &apos;D33691FC-7EB9-4D1C-888C-4F4B6E204680&apos;;
        ///--DECLARE @cycleId INT = 1;
        ///
        ///
        /// SET NOCOUNT ON;
        ///
        ///    SELECT DISTINCT
        ///         empGoal.CompId
        ///        ,empGoal.EMP_Info_Id
        ///		,emp.FullName
        ///    FROM PMS_EmployeeGoals as empGoal
        ///		INNER JOIN EMP_Info AS emp ON empGoal.EMP_Info_Id = emp.Id
        ///    WHERE 
        ///        empGoal.CompId = @CompId
        ///         AND empGoal.MS_PerformanceCycles_Id = @cycleId.
        /// </summary>
        internal static string GetEmployeesGoalsByCompId {
            get {
                return ResourceManager.GetString("GetEmployeesGoalsByCompId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///--Sql.GetEmployeesSelfEvaluationsByStatus
        ///
        ///--select * from PMS_SelfEvaluations
        ///--select * from PMS_SelfEvaluationDetails
        ///
        ///--DECLARE @compId UNIQUEIDENTIFIER = &apos;D33691FC-7EB9-4D1C-888C-4F4B6E204680&apos;;
        ///--DECLARE @status NVARCHAR(50) = &apos;Draft&apos;;
        ///--DECLARE @cycleId INT = 3
        ///
        ///
        ///SELECT pmsSelf.[SelfEvaluationId]
        ///      ,pmsSelf.[MS_PerformanceCycles_CycleId]
        ///	  ,msPmsCycle.CycleName
        ///      ,pmsSelf.[EMP_Info_Id]
        ///	  ,pmsSelfEmp.FullName
        ///      ,pmsSelf.[SubmittedDate]
        ///      ,pmsSelf.[OverallComments]
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetEmployeesSelfEvaluationsByStatus {
            get {
                return ResourceManager.GetString("GetEmployeesSelfEvaluationsByStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///--Sql.GetEmpSelfEvaluationGoalDetailsByCycleAndEmp
        ///
        ///--DECLARE @empId UNIQUEIDENTIFIER = &apos;5DE2FE64-4D6B-4E75-BA75-B43A143BC4BD&apos;
        ///--DECLARE @cycleId INT = 3
        ///
        ///
        ///SELECT pmsSelfDetail.PMS_SelfEvaluations_SelfEvaluationId
        ///	  ,pmsSelfDetail.Id
        ///      ,ISNULL(pmsSelfDetail.PMS_EmployeeGoals_GoalId, empGoal.GoalId) AS &apos;PMS_EmployeeGoals_GoalId&apos;
        ///	  ,msPmsCycle.CycleName
        ///      ,pmsSelfDetail.SelfRating
        ///	  ,pmsSelfEmp.FullName
        ///      ,pmsSelfDetail.Comments
        ///	  ,empGoal.GoalDescription
        ///	  ,empGoal.GoalTitle        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetEmpSelfEvaluationGoalDetailsByCycleAndEmp {
            get {
                return ResourceManager.GetString("GetEmpSelfEvaluationGoalDetailsByCycleAndEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///--Sql.GetGoalDetailsByGoadId
        ///
        ////*
        ///DECLARE @goalId INT = 1010;
        ///DECLARE @compId UNIQUEIDENTIFIER = &apos;C225A53F-9ECB-4B9A-88DC-EAEF6115C2A4&apos;
        ///*/
        ///
        ///select 
        ///		 empGoal.GoalId
        ///		,empGoal.FormDate
        ///		,empGoal.CompId
        ///		,empGoal.EMP_Info_Id
        ///		,emp.FullName AS &apos;EmployeeName&apos;
        ///		,emp.EmpId
        ///		,dept.DepartmentName
        ///		,desg.DesignationName
        ///		,branch.BranchName
        ///		,empGoal.MS_PerformanceCycles_Id
        ///		,pmsCycle.StartDate
        ///		,pmsCycle.EndDate
        ///		,pmsCycle.CycleName
        ///		,empGoal.MS_GoalCategories_CategoryId
        ///		,goalC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetGoalDetailsByGoadId {
            get {
                return ResourceManager.GetString("GetGoalDetailsByGoadId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///--DECLARE @CompId UNIQUEIDENTIFIER = &apos;D33691FC-7EB9-4D1C-888C-4F4B6E204680&apos;;
        ///--DECLARE @FromDt DATE = GETDATE();
        ///--DECLARE @ToDt DATE = GETDATE();
        ///
        ///SELECT goalApp.ApprovalId
        ///      ,goalApp.FormDate
        ///      ,goalApp.CompId
        ///      ,goalApp.ApproverId
        ///	  ,emp.FullName AS &apos;ApproverName&apos;
        ///      ,goalApp.MS_PerformanceCycles_Id
        ///	  ,perfCycle.CycleName
        ///      ,goalApp.MS_GoalCategories_CategoryId
        ///	  ,goalCat.CategoryName
        ///      ,goalApp.PMS_EmployeeGoals_GoalId
        ///	  ,empGoal.GoalTitle
        ///      ,goalApp.Appro [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetGoalsApprovalsByCompId {
            get {
                return ResourceManager.GetString("GetGoalsApprovalsByCompId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///--Sl.GetHRCalibrationReviewsByCycleId
        ///
        ///--select * from PMS_EmployeeGoals
        ///--select * from PMS_SelfEvaluations
        ///--select * from PMS_ManagerEvaluations
        ///--select * from PMS_CalibrationReviews
        ///----UPDATE PMS_CalibrationReviews SET PMS_ManagerEvaluations_Id =1 where Id = 1
        ///
        ///
        ///--DECLARE @compId UNIQUEIDENTIFIER = NEWID();
        ///--DECLARE @cycleId INT = 1
        ///
        ///SELECT 
        ///		 review.Id
        ///		,review.FormDate
        ///		,review.EMP_Info_Id
        ///		,emp.FullName AS &apos;EmployeeName&apos;
        ///		,review.MS_PerformanceCycles_CycleId
        ///		,cycle.C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetHRCalibrationReviewsByCycleId {
            get {
                return ResourceManager.GetString("GetHRCalibrationReviewsByCycleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///--select * from PMS_ManagerEvaluations
        ///
        ///--DECLARE @compId UNIQUEIDENTIFIER  = &apos;D33691FC-7EB9-4D1C-888C-4F4B6E204680&apos;
        ///--DECLARE @FromDt DATE = &apos;2026-05-28&apos;
        ///--DECLARE @ToDt DATE = &apos;2026-05-29&apos;
        ///
        ///SELECT mngrEval.Id
        ///      ,mngrEval.EMP_Info_Id
        ///	  ,emp.FullName AS &apos;EmpName&apos;
        ///      ,mngrEval.ManagerId
        ///	  ,empMngr.FullName AS &apos;ManagerName&apos; 
        ///      ,mngrEval.MS_PerformanceCycles_CycleId
        ///	  ,permCycle.CycleName
        ///      ,mngrEval.OverallRating
        ///      ,mngrEval.OverallComments
        ///      ,mngrEval.SubmittedDat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetManagerEvaluationsByDates {
            get {
                return ResourceManager.GetString("GetManagerEvaluationsByDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///--Sql.GetEmployeesSelfEvaluationsByMngrId
        ///
        ///--DECLARE @compId UNIQUEIDENTIFIER  = &apos;D33691FC-7EB9-4D1C-888C-4F4B6E204680&apos;
        ///--DECLARE @managerId UNIQUEIDENTIFIER  = &apos;EA186978-58F9-4153-9863-DCD4E7AF4F18&apos;
        ///--DECLARE @status NVARCHAR(50) = &apos;draft&apos;
        ///
        ///SELECT mngrEval.Id
        ///      ,mngrEval.EMP_Info_Id
        ///	  ,emp.FullName AS &apos;EmpName&apos;
        ///      ,mngrEval.ManagerId
        ///	  ,empMngr.FullName AS &apos;ManagerName&apos; 
        ///      ,mngrEval.MS_PerformanceCycles_CycleId
        ///	  ,permCycle.CycleName
        ///      ,mngrEval.OverallRating
        ///      ,mngrEv [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetManagerEvaluationsByMngrId {
            get {
                return ResourceManager.GetString("GetManagerEvaluationsByMngrId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---GetMngrEvaluatedEmpByCycleId.Sql
        ///
        ///--DECLARE @status NVARCHAR(50) = &apos;Submitted&apos;
        ///--DECLARE @cycleId INT = 4
        ///
        ///SELECT 
        ///	 mngrEval.EMP_Info_Id
        ///	,emp.FullName AS &apos;EmployeeName&apos;
        ///	FROM PMS_ManagerEvaluations AS mngrEval
        ///		INNER JOIN EMP_Info AS emp ON emp.Id = mngrEval.EMP_Info_Id AND emp.IsActive = 1
        ///		INNER JOIN MS_PerformanceCycles AS cycle ON cycle.CycleId = mngrEval.MS_PerformanceCycles_CycleId
        ///			AND cycle.Active = 1
        ///	WHERE mngrEval.Active = 1
        ///		AND mngrEval.MS_PerformanceCycles_CycleId = @cyc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetMngrEvaluatedEmpByCycleId {
            get {
                return ResourceManager.GetString("GetMngrEvaluatedEmpByCycleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///--Sql.GetMngrEvaluationGoalDetailsByCycleAndEmp
        ///
        ///--DECLARE @empId UNIQUEIDENTIFIER = &apos;5DE2FE64-4D6B-4E75-BA75-B43A143BC4BD&apos;
        ///--DECLARE @cycleId INT = 3
        ///
        ///
        ///SELECT 
        ///	   pmsSelfDetail.PMS_EmployeeGoals_GoalId
        ///	  ,msPmsCycle.CycleName
        ///      ,pmsSelfDetail.SelfRating
        ///	  ,pmsSelfEmp.FullName
        ///      ,pmsSelfDetail.Comments
        ///	  ,empGoal.GoalDescription
        ///	  ,empGoal.GoalTitle
        ///	  ,pmsSelfEval.OverallComments
        ///	  ,mngrEval.Id AS &apos;PMS_ManagerEvaluations_Id&apos;
        ///	  ,mngrEval.ManagerId
        ///	  ,mngrEval.OverallRating [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetMngrEvaluationGoalDetailsByCycleAndEmp {
            get {
                return ResourceManager.GetString("GetMngrEvaluationGoalDetailsByCycleAndEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///---Sql.GetPerformanceOutcomesByCycleId
        ///
        ///--DECLARE @cycleId INT = 4;
        ///
        ///SELECT 
        ///		 calibration.Id AS &apos;PMS_CalibrationReviews_Id&apos;
        ///		,calibration.MS_PerformanceCycles_CycleId
        ///		,calibration.FinalRating
        ///		,calibration.EMP_Info_Id
        ///		,emp.FullName AS &apos;EmployeeName&apos;
        ///		,perfOutcms.Id
        ///		,perfOutcms.MS_PerformanceBand_Id
        ///		,perfOutcms.BonusEligible
        ///		,perfOutcms.PromotionRecommendation
        ///		,perfOutcms.PromotionEligible
        ///		,perfOutcms.BonusAmount
        ///		,perfOutcms.IncrementPercentage
        ///		,perfOutcms.Developmen [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetPerformanceOutcomesByCycleId {
            get {
                return ResourceManager.GetString("GetPerformanceOutcomesByCycleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///-- GetPMSFeedbackDetailsByCycleId.Sql
        ///
        ///
        ////*
        ///DECLARE @cycleId INT = 1
        ///
        ///*/
        ///
        ///
        ///SELECT pmsFedbck.Id
        ///      ,pmsFedbck.FromEmployeeId
        ///	  ,Fromemp.FullName AS &apos;FromEmployeeName&apos;
        ///      ,pmsFedbck.ToEmployeeId
        ///	  ,Toemp.FullName AS &apos;ToEmployeeName&apos;
        ///      ,pmsFedbck.MS_PerformanceCycles_CycleId
        ///	  ,cycle.CycleName
        ///      ,pmsFedbck.FeedbackType
        ///      ,pmsFedbck.FeedbackText
        ///      ,pmsFedbck.Rating
        ///      ,pmsFedbck.SubmittedDate
        ///  FROM [PMS_Feedbacks] AS pmsFedbck
        ///	INNER JOIN EMP_Info AS Fromemp ON [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetPMSFeedbackDetailsByCycleId {
            get {
                return ResourceManager.GetString("GetPMSFeedbackDetailsByCycleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///---UpsertEmpFeedback.Sql
        ///
        ///
        ///--select * from PMS_Feedbacks
        ///
        ///--DECLARE @Id                               INT = 1;
        ///--DECLARE @MachineId                        NVARCHAR(50) = &apos;Id11&apos;
        ///--DECLARE @MachineIp                        NVARCHAR(50) = &apos;Ip&apos;
        ///--DECLARE @CompId                           UNIQUEIDENTIFIER = &apos;D33691FC-7EB9-4D1C-888C-4F4B6E204680&apos;
        ///--DECLARE @FromEmployeeId                   UNIQUEIDENTIFIER = &apos;EA186978-58F9-4153-9863-DCD4E7AF4F18&apos;;
        ///--DECLARE @ToEmployeeId                     UNIQUEID [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpsertEmpFeedback {
            get {
                return ResourceManager.GetString("UpsertEmpFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  
        ///
        /// ---UpsertEmpGoalApproval.Sql
        ///
        ///-- DECLARE @json NVARCHAR(MAX) = N&apos;
        ///-- [
        ///--  {
        ///--    &quot;ApprovalId&quot;: 0,
        ///--    &quot;FormDate&quot;: &quot;2026-05-28T10:00:00&quot;,
        ///--    &quot;MachineId&quot;: &quot;M1&quot;,
        ///--    &quot;MachineIp&quot;: &quot;192.168.1.10&quot;,
        ///--    &quot;CompId&quot;: &quot;D33691FC-7EB9-4D1C-888C-4F4B6E204680&quot;,
        ///--    &quot;ApproverId&quot;: &quot;C7716840-5EEE-4EC7-8E10-2AAF274252AD&quot;,
        ///--    &quot;MS_PerformanceCycles_Id&quot;: 1,
        ///--    &quot;MS_GoalCategories_CategoryId&quot;: 1,
        ///--    &quot;PMS_EmployeeGoals_GoalId&quot;: 5,
        ///--    &quot;ApprovalStatus&quot;: &quot;Approved&quot;,
        ///--    &quot;Comment&quot;: &quot;Good w [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpsertEmpGoalApproval {
            get {
                return ResourceManager.GetString("UpsertEmpGoalApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///--DECLARE @CheckInId                 INT = 0;
        ///--DECLARE @MachineId                 NVARCHAR(50) = &apos;ID&apos;;
        ///--DECLARE @MachineIp                 NVARCHAR(50) = &apos;Ip&apos;;
        ///--DECLARE @CompId                    UNIQUEIDENTIFIER = NEWID();
        ///--DECLARE @PMS_EmployeeGoals_GoalId  INT = 5;
        ///--DECLARE @ProgressPercentage        DECIMAL(5,2) = 22;
        ///--DECLARE @Comments                  NVARCHAR(MAX) = &apos;test&apos;;
        ///--DECLARE @AttachmentPath            NVARCHAR(MAX) = &apos;test&apos;;
        ///--DECLARE @Active                    BIT = 1;
        ///-- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpsertEmpGoalProgress {
            get {
                return ResourceManager.GetString("UpsertEmpGoalProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  
        ///
        /// 
        ///
        /// --select NEWID()
        /// --select * from PMS_EmployeeGoals
        /// --select top 100 * from EMP_Info order by FormDate desc
        ///
        ///-- DECLARE @json NVARCHAR(MAX) = &apos;[
        ///--  {
        ///--    &quot;GoalId&quot;: 5,
        ///--    &quot;FormDate&quot;: &quot;2026-05-28T00:00:00&quot;,
        ///--    &quot;MachineId&quot;: &quot;D33691FC-7EB9-4D1C-888C-4F4B6E204680&quot;,
        ///--    &quot;MachineIp&quot;: &quot;192.168.1.10&quot;,
        ///--    &quot;CompId&quot;: &quot;D33691FC-7EB9-4D1C-888C-4F4B6E204680&quot;,
        ///--    &quot;EMP_Info_Id&quot;: &quot;EA186978-58F9-4153-9863-DCD4E7AF4F18&quot;,
        ///--    &quot;MS_PerformanceCycles_Id&quot;: 1,
        ///--    &quot;MS_GoalCategories_Cate [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpsertEmployeeGoals {
            get {
                return ResourceManager.GetString("UpsertEmployeeGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///--select * from PMS_SelfEvaluations
        ///
        ///--DECLARE @SelfEvaluationId                 INT = 0;
        ///--DECLARE @MachineId                        NVARCHAR(50) = &apos;Id&apos;
        ///--DECLARE @MachineIp                        NVARCHAR(50) = &apos;Ip&apos;
        ///--DECLARE @CompId                           UNIQUEIDENTIFIER = &apos;D33691FC-7EB9-4D1C-888C-4F4B6E204680&apos;
        ///--DECLARE @MS_PerformanceCycles_CycleId     INT = 1;
        ///--DECLARE @EMP_Info_Id                      UNIQUEIDENTIFIER = &apos;EA186978-58F9-4153-9863-DCD4E7AF4F18&apos;;
        ///--DECLARE @SubmittedDate   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpsertEmpSelfEvaluation {
            get {
                return ResourceManager.GetString("UpsertEmpSelfEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /******************************************************************
        ///MULTIPLE ROW UPSERT USING OPENJSON
        ///TABLE: [HRMS].[dbo].[PMS_SelfEvaluationDetails]
        ///******************************************************************/
        ///--select * from PMS_SelfEvaluationDetails
        ///
        ///--DECLARE @Json NVARCHAR(MAX) = N&apos;
        ///--[
        ///--    {
        ///--        &quot;Id&quot;: 10,
        ///--        &quot;FormDate&quot;: &quot;2026-05-28&quot;,
        ///--        &quot;MachineId&quot;: &quot;Id&quot;,
        ///--        &quot;MachineIp&quot;: &quot;192.168.1.10&quot;,
        ///--        &quot;CompId&quot;: &quot;D33691FC-7EB9-4D1C-888C-4F4B6E204680&quot;,
        ///--    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpsertEmpSelfEvaluationDetails {
            get {
                return ResourceManager.GetString("UpsertEmpSelfEvaluationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  
        ///
        /// ---Sql.UpsertHRCalibrationReviews
        ///
        ///--select * from PMS_EmployeeGoals
        ///--select * from PMS_SelfEvaluations
        ///--select * from PMS_ManagerEvaluations
        ///--select * from PMS_CalibrationReviews
        ///
        ///
        ///--DECLARE @Json NVARCHAR(MAX) = N&apos;[
        ///--  {
        ///--    &quot;Id&quot;: 1,
        ///--    &quot;FormDate&quot;: &quot;2025-01-15&quot;,
        ///--    &quot;MachineId&quot;: &quot;PC001&quot;,
        ///--    &quot;MachineIp&quot;: &quot;192.168.1.10&quot;,
        ///--    &quot;CompId&quot;: &quot;D33691FC-7EB9-4D1C-888C-4F4B6E204680&quot;,
        ///--    &quot;EMP_Info_Id&quot;: &quot;EA186978-58F9-4153-9863-DCD4E7AF4F18&quot;,
        ///--    &quot;MS_PerformanceCycles_CycleId&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpsertHRCalibrationReviews {
            get {
                return ResourceManager.GetString("UpsertHRCalibrationReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///--select * from PMS_ManagerEvaluations
        ///
        ///--DECLARE @Id                               INT = 1;
        ///--DECLARE @MachineId                        NVARCHAR(50) = &apos;Id&apos;
        ///--DECLARE @MachineIp                        NVARCHAR(50) = &apos;Ip&apos;
        ///--DECLARE @CompId                           UNIQUEIDENTIFIER = &apos;D33691FC-7EB9-4D1C-888C-4F4B6E204680&apos;
        ///--DECLARE @EMP_Info_Id                      UNIQUEIDENTIFIER = &apos;EA186978-58F9-4153-9863-DCD4E7AF4F18&apos;;
        ///--DECLARE @ManagerId                        UNIQUEIDENTIFIER = &apos;EA186978-58F9 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpsertManagerEvaluation {
            get {
                return ResourceManager.GetString("UpsertManagerEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///--select * from PMS_ManagerEvaluations
        ///--select * from PMS_ManagerEvaluationDetails
        ///
        ///--DECLARE @Json NVARCHAR(MAX) = N&apos;
        ///--[
        ///--  {
        ///--    &quot;Id&quot;: 1,
        ///--    &quot;FormDate&quot;: &quot;2026-05-29&quot;,
        ///--    &quot;MachineId&quot;: &quot;PC001&quot;,
        ///--    &quot;MachineIp&quot;: &quot;192.168.1.1&quot;,
        ///--    &quot;CompId&quot;: &quot;D33691FC-7EB9-4D1C-888C-4F4B6E204680&quot;,
        ///--    &quot;PMS_ManagerEvaluations_Id&quot;: 1,
        ///--    &quot;PMS_EmployeeGoals_GoalId&quot;: 5,
        ///--    &quot;ManagerRating&quot;: 4,
        ///--    &quot;ManagerComments&quot;: &quot;Excellent&quot;,
        ///--    &quot;Active&quot;: true,
        ///--    &quot;CreatedBy&quot;: &quot;7EC2A3C8-554F-4F38 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpsertManagerEvaluationDetails {
            get {
                return ResourceManager.GetString("UpsertManagerEvaluationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///BEGIN
        ///
        ///    BEGIN TRY
        ///
        ///--DECLARE @Json NVARCHAR(MAX) = 
        ///--N&apos;
        ///--[
        ///--  {
        ///--    &quot;Id&quot;: 0,
        ///--    &quot;FormDate&quot;: &quot;2026-06-01&quot;,
        ///--    &quot;MachineId&quot;: &quot;Id&quot;,
        ///--    &quot;MachineIp&quot;: &quot;192.168.1.1&quot;,
        ///--    &quot;CompId&quot;: &quot;C225A53F-9ECB-4B9A-88DC-EAEF6115C2A4&quot;,
        ///--    &quot;EMP_Info_Id&quot;: &quot;EA186978-58F9-4153-9863-DCD4E7AF4F18&quot;,
        ///--    &quot;MS_PerformanceCycles_CycleId&quot;: 4,
        ///--	&quot;PMS_CalibrationReviews_Id&quot;: 8,
        ///--    &quot;FinalRating&quot;: 4.5155,
        ///--    &quot;MS_PerformanceBand_Id&quot;: 2,
        ///--    &quot;BonusEligible&quot;: true,
        ///--    &quot;PromotionRecommendati [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpsertPerformanceOutcomes {
            get {
                return ResourceManager.GetString("UpsertPerformanceOutcomes", resourceCulture);
            }
        }
    }
}
