//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerModel.SqlAccess.ESS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EssSql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EssSql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServerModel.SqlAccess.ESS.EssSql", typeof(EssSql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///---Sql.AddUpdateEmployeeLeaves
        ///
        ////*
        ///
        ///DECLARE @employeeId uniqueidentifier = &apos;00000000-0000-0000-0000-000000000000&apos;
        ///DECLARE @compId uniqueidentifier = &apos;00000000-0000-0000-0000-000000000000&apos;
        ///DECLARE @createdBy uniqueidentifier =  &apos;00000000-0000-0000-0000-000000000000&apos;
        ///DECLARE @id uniqueidentifier = &apos;00000000-0000-0000-0000-000000000000&apos;
        ///DECLARE @MS_Leave_Id INT = 0;
        ///DECLARE @TotalLeaves DECIMAL(18, 4) = 0;
        ///DECLARE @AvailableLeves DECIMAL(18, 4) = 0;
        /// */
        ///
        ///
        ///If(@id = &apos;00000000-0000-0000-0000-000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddUpdateEmployeeLeaves {
            get {
                return ResourceManager.GetString("AddUpdateEmployeeLeaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///--ApproveReimbursementClaims.Sql
        ///
        ///--select * from Reim_Appro_Claims
        ///
        ///--DECLARE @Id uniqueidentifier = &apos;A07A840F-B53B-472B-910F-558C5958E9A6&apos;;
        ///--DECLARE @CompId uniqueidentifier = &apos;00000000-0000-0000-0000-000000000000&apos;;
        ///--DECLARE @Reim_Claims_Id uniqueidentifier = &apos;D33691FC-7EB9-4D1C-888C-4F4B6E204680&apos;;
        ///--DECLARE @Approver_Emp_Id UNIQUEIDENTIFIER = &apos;00000000-0000-0000-0000-000000000000&apos;;
        ///--DECLARE @Status nvarchar(50) = &apos;Monthly&apos;;
        ///--DECLARE @MachineId nvarchar(50) = &apos;AJINKYA-PC&apos;;
        ///--DECLARE @M [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ApproveReimbursementClaims {
            get {
                return ResourceManager.GetString("ApproveReimbursementClaims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ////*
        ///---GetEmployeeAvailableLeavesById.Sql
        ///
        ///DECLARE @empId UNIQUEIDENTIFIER = &apos;90DAA615-055D-44B1-84F7-905C9E904791&apos;
        ///
        ///*/
        ///
        ///select empLeaves.Id,
        ///		empLeaves.CompId,
        ///		empLeaves.EMP_Info_Id, 
        ///		emp.FullName, 
        ///		leave.LeaveName, 
        ///		empLeaves.MS_Leave_Id, 
        ///		TotalLeaves, 
        ///		AvailableLeaves
        ///	from EMP_Leaves as empLeaves
        ///		INNER JOIN MS_Leave as leave on leave.Id = empLeaves.MS_Leave_Id
        ///		INNER JOIN EMP_Info As emp on emp.Id = empLeaves.EMP_Info_Id
        ///		where empLeaves.EMP_Info_Id = @empId
        ///			and [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetEmployeeAvailableLeavesById {
            get {
                return ResourceManager.GetString("GetEmployeeAvailableLeavesById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ////**
        ///----GetEmployeeLeaveReqsByCompId.Sql
        ///
        ///DECLARE @Id UNIQUEIDENTIFIER = &apos;00000000-0000-0000-0000-000000000000&apos;
        ///
        ///
        ///**/
        ///
        ///SELECT  empLvReq.Id
        ///      ,empLvReq.FormDate
        ///      ,empLvReq.CompId
        ///      ,empLvReq.CreatedBy
        ///      ,empLvReq.EMP_Info_Id
        ///	  ,emp.FullName
        ///      ,empLvReq.MS_Leave_Id
        ///	  ,lv.LeaveName
        ///      ,empLvReq.FromDate
        ///      ,empLvReq.ToDate
        ///      ,empLvReq.TotalDays
        ///      ,empLvReq.LeaveFor
        ///      ,empLvReq.LeaveReason
        ///      ,empLvReq.IsApprovedBy
        ///	  ,empApp.FullName AS &apos;Appro [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetEmployeeLeaveReqById {
            get {
                return ResourceManager.GetString("GetEmployeeLeaveReqById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///---Sql.GetEmployeeLeaveReqByLeaveStatusAndCompId
        ///
        ////*
        ///DECLARE @compId UNIQUEIDENTIFIER = &apos;00000000-0000-0000-0000-000000000000&apos;
        ///DECLARE @leaveStatus INT = 1
        ///
        ///*/
        ///
        ///SELECT 
        ///		 empLvReq.Id
        ///		,empLvReq.EMP_Info_Id
        ///		,emp.FullName
        ///		,empLvReq.MS_Leave_Id
        ///		,lv.LeaveName
        ///		,empLvReq.FromDate
        ///		,empLvReq.ToDate
        ///		,empLvReq.TotalDays AS &apos;Applied Days&apos;
        ///		,empLv.AvailableLeaves
        ///		,empLv.Id AS &apos;EMP_Leaves_Id&apos;
        ///		,empLvReq.LeaveStatus
        ///		,empLvReq.IsApprovedBy
        ///		,CASE 
        ///			WHEN empApprover.FullName I [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetEmployeeLeaveReqByLeaveStatusAndCompId {
            get {
                return ResourceManager.GetString("GetEmployeeLeaveReqByLeaveStatusAndCompId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ////**
        ///----GetEmployeeLeaveReqsByCompId.Sql
        ///
        ///DECLARE @compId UNIQUEIDENTIFIER = &apos;00000000-0000-0000-0000-000000000000&apos;
        ///
        ///
        ///**/
        ///
        ///SELECT  empLvReq.Id
        ///      ,empLvReq.FormDate
        ///      ,empLvReq.CompId
        ///      ,empLvReq.CreatedBy
        ///      ,empLvReq.EMP_Info_Id
        ///	  ,emp.FullName
        ///      ,empLvReq.MS_Leave_Id
        ///	  ,lv.LeaveName
        ///      ,empLvReq.FromDate
        ///      ,empLvReq.ToDate
        ///      ,empLvReq.TotalDays
        ///      ,empLvReq.LeaveFor
        ///      ,empLvReq.LeaveReason
        ///      ,empLvReq.IsApprovedBy
        ///	  ,empApp.FullName AS &apos;A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetEmployeeLeaveReqsByCompId {
            get {
                return ResourceManager.GetString("GetEmployeeLeaveReqsByCompId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ////*
        ///DECLARE @compId UNIQUEIDENTIFIER = &apos;00000000-0000-0000-0000-000000000000&apos;
        ///*/
        ///
        ///SELECT empLn.Id
        ///      ,empLn.FormDate
        ///      ,empLn.MachineId
        ///      ,empLn.MachineIp
        ///      ,empLn.CompId
        ///      ,empLn.EMP_Info_Id
        ///	  ,emp.FullName
        ///      ,empLn.MS_LN_Id
        ///	  ,ln.LNTypeName
        ///	  ,ln.InterestRate
        ///      ,empLn.ReqAmt
        ///      ,empLn.ApprAmt
        ///      ,empLn.TenureMonths
        ///      ,empLn.Status
        ///      ,empLn.Remark
        ///      ,empLn.Ammend
        ///      ,empLn.Active
        ///  FROM EMP_LNReq AS empLn
        ///		INNER JOIN EMP_Info AS emp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetEmployeeLoanRequestByCompId {
            get {
                return ResourceManager.GetString("GetEmployeeLoanRequestByCompId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ////**
        ///----GetReimbursementClaimsByCompId.Sql
        ///
        ///DECLARE @CompId UNIQUEIDENTIFIER = &apos;00000000-0000-0000-0000-000000000000&apos;
        ///
        ///
        ///**/
        ///
        ///select 
        ///		 claim.Id
        ///		,claim.CompId
        ///		,claim.EMP_Info_Id
        ///		,emp.FullName
        ///		,emp.MS_Branch_Id
        ///		,empBranch.BranchName
        ///		,claim.MS_Reim_Types_Id
        ///		,reimb.ReimbursementType
        ///		,claim.ClaimDate
        ///		,claim.GSTRegNos
        ///		,claim.CGST
        ///		,claim.SGST
        ///		,claim.Amount
        ///		,claim.Description
        ///		,claim.BillPath
        ///		,claim.Status
        ///		,claim.SubmittedDate
        ///		,claim.ApprovedDate
        ///		,cla [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetReimbursementClaimsByCompId {
            get {
                return ResourceManager.GetString("GetReimbursementClaimsByCompId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ////**
        ///----GetReimbursementClaimsByCompIdAndBranchId.sql.Sql
        ///
        ///DECLARE @CompId UNIQUEIDENTIFIER = &apos;00000000-0000-0000-0000-000000000000&apos;
        ///DECLARE @BranchId int = 5004;
        ///
        ///**/
        ///
        ///select 
        ///		 claim.Id
        ///		,claim.CompId
        ///		,claim.EMP_Info_Id
        ///		,emp.FullName
        ///		,emp.MS_Branch_Id
        ///		,empBranch.BranchName
        ///		,claim.MS_Reim_Types_Id
        ///		,reimb.ReimbursementType
        ///		,claim.ClaimDate
        ///		,claim.GSTRegNos
        ///		,claim.CGST
        ///		,claim.SGST
        ///		,claim.Amount
        ///		,claim.Description
        ///		,claim.BillPath
        ///		,claim.Status
        ///		,claim. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetReimbursementClaimsByCompIdAndBranchId {
            get {
                return ResourceManager.GetString("GetReimbursementClaimsByCompIdAndBranchId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ////**
        ///----GetReimbursementClaimsByCompId.Sql
        ///
        ///DECLARE @EmpId UNIQUEIDENTIFIER = &apos;00000000-0000-0000-0000-000000000000&apos;
        ///
        ///
        ///**/
        ///
        ///select 
        ///		 claim.Id
        ///		,claim.CompId
        ///		,claim.EMP_Info_Id
        ///		,emp.FullName
        ///		,emp.MS_Branch_Id
        ///		,empBranch.BranchName
        ///		,claim.MS_Reim_Types_Id
        ///		,reimb.ReimbursementType
        ///		,claim.ClaimDate
        ///		,claim.GSTRegNos
        ///		,claim.CGST
        ///		,claim.SGST
        ///		,claim.Amount
        ///		,claim.Description
        ///		,claim.BillPath
        ///		,claim.Status
        ///		,claim.SubmittedDate
        ///		,claim.ApprovedDate
        ///		,clai [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetReimbursementClaimsByEmpId {
            get {
                return ResourceManager.GetString("GetReimbursementClaimsByEmpId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///---Sql.UpdateEmployeeLeaveRequestStatusByIdAndStatus
        ///
        ////*
        ///DECLARE @approverId uniqueidentifier = &apos;AB159B4D-B47A-4545-88F3-4D763F23A4B6&apos;;
        ///DECLARE @leaveStatus INT = 1;
        ///DECLARE @id uniqueidentifier =&apos;AB159B4D-B47A-4545-88F3-4D763F23A4B6&apos;;
        ///
        ///*/
        ///
        ///IF(@leaveStatus = 2)
        ///BEGIN
        ///	UPDATE empLv SET empLv.AvailableLeaves = CASE 
        ///											   WHEN empLv.AvailableLeaves &gt;= empLvReq.TotalDays 
        ///											     THEN empLv.AvailableLeaves - empLvReq.TotalDays
        ///											   ELSE empLv.AvailableLeaves  -- OR 0  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpdateEmployeeLeaveRequestStatusByIdAndStatus {
            get {
                return ResourceManager.GetString("UpdateEmployeeLeaveRequestStatusByIdAndStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///--UpsetLoanTypes.Sql
        ///
        ////*
        ///--select * from EMP_LNReq
        ///
        ///DECLARE @Id uniqueidentifier = &apos;F155BDB3-1DCD-448C-9972-44D1F4623421&apos;;
        ///DECLARE @FormDate DATETIME2 = GETDATE();
        ///DECLARE @MachineId NVARCHAR(50) = &apos;&apos;;
        ///DECLARE @MachineIp NVARCHAR(50) = &apos;&apos;;
        ///DECLARE @CompId uniqueidentifier = &apos;00000000-0000-0000-0000-000000000000&apos;;
        ///DECLARE @EMP_Info_Id uniqueidentifier = &apos;00000000-0000-0000-0000-000000000000&apos;;
        ///DECLARE @MS_LN_Id INT = 1;
        ///DECLARE @ReqAmt DECIMAL(18, 4) = 100;
        ///DECLARE @ApprAmt DECIMAL(18, 4) = 0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpsertEmployeeLoanRequest {
            get {
                return ResourceManager.GetString("UpsertEmployeeLoanRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ////*
        ///--UpsertReimbursementClaims.Sql
        ///
        ///--select * from Reim_Claims
        ///
        ///DECLARE @Id uniqueidentifier = &apos;A07A840F-B53B-472B-910F-558C5958E9A6&apos;;
        ///DECLARE @CompId uniqueidentifier = &apos;00000000-0000-0000-0000-000000000000&apos;;
        ///DECLARE @EMP_Info_Id uniqueidentifier = &apos;D33691FC-7EB9-4D1C-888C-4F4B6E204680&apos;;
        ///DECLARE @MS_Reim_Types_Id INT = 1;
        ///DECLARE @ClaimDate DATETIME = GETDATE();
        ///DECLARE @GSTRegNos NVARCHAR(100) = &apos;abc&apos;;
        ///DECLARE @CGST DECIMAL(18, 4) = 1000;
        ///DECLARE @SGST DECIMAL(18, 4) = 1000;
        ///DECLARE @Amoun [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpsertReimbursementClaims {
            get {
                return ResourceManager.GetString("UpsertReimbursementClaims", resourceCulture);
            }
        }
    }
}
