//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerModel.SqlAccess.Reports {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServerModel.SqlAccess.Reports.Sql", typeof(Sql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///--select * from EMP_Info
        ///--select * from MS_Designation
        ///
        ///--select * from MS_Shift
        ////**
        ///DECLARE @compId UNIQUEIDENTIFIER = &apos;C225A53F-9ECB-4B9A-88DC-EAEF6115C2A4&apos;;
        ///DECLARE @branchId INT = 6007;
        ///
        ///*/
        ///
        ///SELECT
        ///	 empMain.Id
        ///	,empMain.EmpId
        ///	,empMain.EmpType
        ///	,empMain.FullName
        ///	,empMain.Gender
        ///	,empMain.DOB
        ///	,empMain.PANNo
        ///	,empMain.AadharNo
        ///	,empMain.MS_Designation_Id
        ///	,desg.DesignationName
        ///	,desg.DesignationCode
        ///	,empMain.MS_Dept_Id
        ///	,dept.DepartmentName
        ///	,dept.DepartmentCode
        ///	,empMain.M [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BranchWiseEmpReports {
            get {
                return ResourceManager.GetString("BranchWiseEmpReports", resourceCulture);
            }
        }
    }
}
