//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerModel.SqlAccess.Attendance {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServerModel.SqlAccess.Attendance.Sql", typeof(Sql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///----- Sql.GetEmployeePunchesById
        ///
        ///--DECLARE @EmpId UNIQUEIDENTIFIER = &apos;90DAA615-055D-44B1-84F7-905C9E904791&apos;; -- Set desired employee ID
        ///--DECLARE @Month INT = 5;   
        ///--DECLARE @Year INT = 2025;  
        ///
        ///DECLARE @MonthStart DATE = DATEFROMPARTS(@Year, @Month, 1);
        ///DECLARE @MonthEnd DATE = EOMONTH(@MonthStart);
        ///
        ///-- Generate calendar dates for the month
        ///WITH Calendar AS (
        ///    SELECT @MonthStart AS WorkDate
        ///    UNION ALL
        ///    SELECT DATEADD(DAY, 1, WorkDate)
        ///    FROM Calendar
        ///    WHERE WorkDate &lt; @Mo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetEmployeePunchesById {
            get {
                return ResourceManager.GetString("GetEmployeePunchesById", resourceCulture);
            }
        }
    }
}
