//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerModel.SqlAccess.HR {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HRSqls {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HRSqls() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServerModel.SqlAccess.HR.HRSqls", typeof(HRSqls).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ////*
        ///
        ///--select * from EMP_Info
        ///--select * from EMP_LNReq
        ///
        ///DECLARE @compId UNIQUEIDENTIFIER = &apos;00000000-0000-0000-0000-000000000000&apos;
        ///DECLARE @status NVARCHAR(50) = &apos;Pending&apos;
        ///
        ///*/
        ///
        ///
        ///SELECT hrLnreq.Id
        ///      ,empLnReq.FormDate
        ///      ,hrLnreq.MachineId
        ///      ,hrLnreq.MachineIp
        ///      ,empLnReq.CompId
        ///      ,empLnReq.Id AS &apos;EMP_LNReq_Id&apos;
        ///	   ,empLnReq.TenureMonths
        ///	  ,Ln.LNTypeName
        ///	  ,Ln.InterestRate
        ///	  ,Ln.MaxAmount
        ///	  ,Ln.IsMaxAmtManual
        ///	  ,msSl.SalaryHeadName
        ///	  ,Ln.MS_SLHead_Id
        ///	  ,Ln.P [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetHRLoanRequestsByStatus {
            get {
                return ResourceManager.GetString("GetHRLoanRequestsByStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///--UpsertHRLoanRequest.Sql
        ///
        ////*
        ///--select * from HR_LNReq
        ///
        ///DECLARE @Id uniqueidentifier = &apos;A07A840F-B53B-472B-910F-558C5958E9A6&apos;;
        ///DECLARE @CompId uniqueidentifier = &apos;00000000-0000-0000-0000-000000000000&apos;;
        ///DECLARE @EMP_LNReq_Id uniqueidentifier = &apos;D33691FC-7EB9-4D1C-888C-4F4B6E204680&apos;;
        ///DECLARE @ApproverId uniqueidentifier = &apos;D33691FC-7EB9-4D1C-888C-4F4B6E204680&apos;;
        ///DECLARE @Status NVARCHAR(50) = &apos;Approved&apos;
        ///DECLARE @Remark nvarchar(MAX) = &apos;remark&apos;;
        ///
        ///*/
        ///
        ///MERGE INTO HR_LNReq as Target
        ///USING (selec [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpsertHRLoanRequest {
            get {
                return ResourceManager.GetString("UpsertHRLoanRequest", resourceCulture);
            }
        }
    }
}
