//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerModel.SqlAccess.EmployeeSetup.AssetInfo.Sql {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServerModel.SqlAccess.EmployeeSetup.AssetInfo.Sql.Sql", typeof(Sql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///----UpsertEmployeeAssetDetails.Sql
        ///
        ///--select * from EMP_Asset
        ///--select * from EMP_AssetDetail
        ///
        ///--truncate table EMP_Asset
        ///--truncate table EMP_AssetDetail
        ///
        ///
        ///--DECLARE @json1 NVARCHAR(MAX) = 
        ///--&apos;[{
        ///--    &quot;Id&quot;: &quot;00000000-0000-0000-0000-000000000000&quot;,
        ///--    &quot;FormDate&quot;: &quot;2023-01-25 23:33:32.017&quot;,
        ///--    &quot;CompId&quot;: &quot;00000000-0000-0000-0000-000000000000&quot;,
        ///--    &quot;EMP_Info_Id&quot;: &quot;566E3EC9-41E2-4EB5-A33A-FF92BFBE2CBE&quot;,
        ///--    &quot;CreatedBy&quot;: &quot;00000000-0000-0000-0000-000000000000&quot;,
        ///--    &quot;Active&quot;: 1
        ///--} [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpsertEmployeeAssetDetails {
            get {
                return ResourceManager.GetString("UpsertEmployeeAssetDetails", resourceCulture);
            }
        }
    }
}
