//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerModel.SqlAccess.EmployeeSetup.FamilyInfo.Sql {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServerModel.SqlAccess.EmployeeSetup.FamilyInfo.Sql.Sql", typeof(Sql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///----select * from [dbo].[EMP_FamilyInfo]
        ///----truncate table [EMP_FamilyInfo]
        ///
        ///
        ///------ UpsertEmployeeFamilyInfo
        ///--DECLARE @empId uniqueidentifier = &apos;3D360BA8-2B12-4DB7-BAC9-9ADFD3553E1E&apos;
        ///
        ///--DECLARE @json nvarchar(max) = 
        ///--&apos;[
        ///--{
        ///--&quot;Id&quot; :&quot;5D0EBD3A-79F4-49B6-8F3F-41433E001AF0&quot;,
        ///--&quot;formdate&quot;: &quot;2023-04-15&quot;,
        ///--&quot;machineIp&quot;:&quot;1.1.1.1&quot;,
        ///--&quot;machineId&quot;:&quot;Machine&quot;,
        ///--&quot;compId&quot; :&quot;00000000-0000-0000-0000-000000000000&quot;,
        ///--&quot;createdby&quot; :&quot;00000000-0000-0000-0000-000000000000&quot;,
        ///--&quot;EMP_Info_Id&quot; :&quot;3D360BA8-2B12- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpsertEmployeeFamilyInfo {
            get {
                return ResourceManager.GetString("UpsertEmployeeFamilyInfo", resourceCulture);
            }
        }
    }
}
