//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerModel.SqlAccess.HelpDesk {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HelpDeskSqls {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HelpDeskSqls() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServerModel.SqlAccess.HelpDesk.HelpDeskSqls", typeof(HelpDeskSqls).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///---Sql.GetHelpDeskTckRepliesByTicketId
        ////*
        ///DECLARE @ticketId INT = 1;
        ///
        ///*/
        ///
        ///SELECT tkreply.Id,
        ///		tkreply.FormDate,
        ///		tkreply.CompId,
        ///		tkreply.HR_HelpDesk_Id,
        ///		tkreply.RepliedByEmpId,
        ///		emp.FullName AS &apos;RepliesEmployeeName&apos;,
        ///		tkreply.Message,
        ///		tkreply.ReplyDate
        ///	FROM HR_HelpDeskReplies  AS tkreply
        ///		INNER JOIN EMP_Info AS emp ON emp.Id = tkreply.RepliedByEmpId
        ///		INNER JOIN HR_HelpDesk AS tk ON tk.Id = tkreply.HR_HelpDesk_Id
        ///		WHERE tkreply.HR_HelpDesk_Id = @ticketId
        ///			AND tk.IsAmmend [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetHelpDeskTckRepliesByTicketId {
            get {
                return ResourceManager.GetString("GetHelpDeskTckRepliesByTicketId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///---Sql.GetHelpDeskTicketInformationByCompId
        ////*
        ///DECLARE @CompId UNIQUEIDENTIFIER = &apos;00000000-0000-0000-0000-000000000000&apos;
        ///
        ///*/
        ///
        ///
        ///SELECT hdTck.Id,
        ///		hdTck.FormDate,
        ///		hdTck.CompId,
        ///		hdTck.EMP_Info_Id,
        ///		emp.FullName AS &apos;EmployeeName&apos;,
        ///		hdTck.MS_TicketCat_Id,
        ///		tk.TicketCategory,
        ///		hdTck.TicketName,
        ///		hdTck.Subject,
        ///		hdTck.Description,
        ///		hdTck.Severity,
        ///		hdTck.AttachmentPath,
        ///		hdTck.AssignEmpId,
        ///		assgEmp.FullName AS &apos;AssignEmployeeName&apos;,
        ///		hdTck.TicketStatus,
        ///		hdTck.TicketResolv [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetHelpDeskTicketInformationByCompId {
            get {
                return ResourceManager.GetString("GetHelpDeskTicketInformationByCompId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///--UpsertReimbursementClaims.Sql
        ///
        ///--select * from HR_HelpDesk
        ///
        ///--DECLARE @Id INT =2;
        ///--DECLARE @CompId uniqueidentifier = &apos;00000000-0000-0000-0000-000000000000&apos;;
        ///--DECLARE @EMP_Info_Id uniqueidentifier = &apos;D33691FC-7EB9-4D1C-888C-4F4B6E204680&apos;;
        ///--DECLARE @MS_TicketCat_Id INT = 1;
        ///--DECLARE @TicketName NVARCHAR(MAX) = &apos;tick 1-2&apos;;
        ///--DECLARE @Subject NVARCHAR(MAX) = &apos;&apos;;
        ///--DECLARE @Description NVARCHAR(MAX) = &apos;&apos;;
        ///--DECLARE @Severity INT = 0;
        ///--DECLARE @AttachmentPath NVARCHAR(MAX) = &apos;&apos;;
        ///--DECLARE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpsertHelpDeskTicketCreation {
            get {
                return ResourceManager.GetString("UpsertHelpDeskTicketCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///--UpsertHelpDeskTicketReplies.Sql
        ///
        ///--select * from HR_HelpDeskReplies
        ///
        ///--DECLARE @Id INT = 0;
        ///--DECLARE @CompId uniqueidentifier = &apos;00000000-0000-0000-0000-000000000000&apos;;
        ///--DECLARE @HR_HelpDesk_Id INT = 4;
        ///--DECLARE @RepliedByEmpId uniqueidentifier = &apos;3E78B576-0307-48FC-8CC3-13D2C6C68A15&apos;;
        ///--DECLARE @Message NVARCHAR(MAX) = &apos;tick 1-2&apos;;
        ///--DECLARE @InterviewStatus NVARCHAR(50) = &apos;InProgress&apos;;
        ///
        ///
        ///
        ///MERGE INTO HR_HelpDeskReplies as Target
        ///USING (select @Id as Id) AS source 
        ///    ON (Target.Id =  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpsertHelpDeskTicketReplies {
            get {
                return ResourceManager.GetString("UpsertHelpDeskTicketReplies", resourceCulture);
            }
        }
    }
}
