//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerModel.SqlAccess.EmployeeSetup.DocumentInfo {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlDocumentUpload {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlDocumentUpload() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServerModel.SqlAccess.EmployeeSetup.DocumentInfo.SqlDocumentUpload", typeof(SqlDocumentUpload).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///--- GetEmployeeDocumentsByDocId.sql.Sql
        ////*
        ///DECLARE @empDocId UNIQUEIDENTIFIER = &apos;3D360BA8-2B12-4DB7-BAC9-9ADFD3553E1E&apos;
        ///
        ///*/
        ///
        ///SELECT  Id
        ///	   ,FormDate
        ///	   ,CompId
        ///	   ,CreatedBy
        ///	   ,EMP_Info_Id
        ///	   ,DocsKey
        ///	   ,DocsValue
        ///	FROM EMP_Docs
        ///	WHERE Id = @empDocId.
        /// </summary>
        internal static string GetEmployeeDocumentsByDocId {
            get {
                return ResourceManager.GetString("GetEmployeeDocumentsByDocId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///--- GetEmployeeDocumentsByEmpId.Sql
        ////*
        ///DECLARE @empId UNIQUEIDENTIFIER = &apos;3D360BA8-2B12-4DB7-BAC9-9ADFD3553E1E&apos;
        ///
        ///*/
        ///
        ///SELECT  Id
        ///	   ,FormDate
        ///	   ,CompId
        ///	   ,CreatedBy
        ///	   ,EMP_Info_Id
        ///	   ,DocsKey
        ///	   ,DocsValue
        ///	FROM EMP_Docs
        ///	WHERE EMP_Info_Id = @empId.
        /// </summary>
        internal static string GetEmployeeDocumentsByEmpId {
            get {
                return ResourceManager.GetString("GetEmployeeDocumentsByEmpId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ////*
        ///--UpsertEmployeeDocumentInfo.Sql
        ///
        ///--select * from EMP_Docs
        ///
        ///DECLARE @Id uniqueidentifier = &apos;00000000-0000-0000-0000-000000000000&apos;;
        ///DECLARE @CompId uniqueidentifier = &apos;00000000-0000-0000-0000-000000000000&apos;;
        ///DECLARE @CreatedBy uniqueidentifier = &apos;00000000-0000-0000-0000-000000000000&apos;;
        ///DECLARE @EMP_Info_Id uniqueidentifier = &apos;00000000-0000-0000-0000-000000000000&apos;;
        ///DECLARE @DocsKey NVARCHAR(100) = &apos;DocName&apos;;
        ///DECLARE @DocsValue NVARCHAR(MAX) = &apos;DocPath&apos;;
        ///
        ///*/
        ///
        ///MERGE INTO EMP_Docs as Target
        ///U [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpsertEmployeeDocumentInfo {
            get {
                return ResourceManager.GetString("UpsertEmployeeDocumentInfo", resourceCulture);
            }
        }
    }
}
