//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerModel.SqlAccess.EmployeeSalarySetup {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServerModel.SqlAccess.EmployeeSalarySetup.Sql", typeof(Sql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///----select * from EMP_SLSetup
        ///----select * from EMP_SLHeads
        ///
        ///----truncate table EMP_SLSetup
        ///----truncate table EMP_SLHeads
        ///
        ///
        ///------ AddUpdateEmployeeSalarySetup
        ///
        ///----DECLARE @machineIp nvarchar(50) = &apos;1.1.1.1&apos;
        ///----DECLARE @machineId nvarchar(50) = &apos;Machine&apos;
        ///----DECLARE @compId uniqueidentifier = &apos;00000000-0000-0000-0000-000000000000&apos;
        ///----DECLARE @empId uniqueidentifier = &apos;00000000-0000-0000-0000-000000000000&apos;
        ///----DECLARE @MS_SLHeads_Id int = 0
        ///----DECLARE @amount DECIMAL(18,10) = 0
        ///----DECL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddUpdateEmpSalarySetup {
            get {
                return ResourceManager.GetString("AddUpdateEmpSalarySetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///--GetEmpSalarySetupDetails
        ///
        ///--DECLARE @compId UNIQUEIDENTIFIER = &apos;00000000-0000-0000-0000-000000000000&apos;
        ///--DECLARE @empId UNIQUEIDENTIFIER = &apos;F4E804F9-6F67-46B0-BB51-69C1E9DCD82D&apos;
        ///
        ///SELECT
        ///	     ISNULL(empSH.Id, &apos;00000000-0000-0000-0000-000000000000&apos;) AS Id
        ///		,ISNULL(empSH.EMP_Info_Id, &apos;00000000-0000-0000-0000-000000000000&apos;) AS EMP_Info_Id
        ///		,emp.FullName
        ///		,sl.Id AS MS_SLHeads_Id
        ///		,sl.SalaryHeadName
        ///		,sl.IsEarningComponent
        ///		,ISNULL(empSH.Amount, 0) AS Amount
        ///		,empslsetup.MS_PayMode_Id
        ///		, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetEmpSalarySetupDetails {
            get {
                return ResourceManager.GetString("GetEmpSalarySetupDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///--GetEmployeeSalarySetup
        ///
        ///--DECLARE @compId uniqueidentifier = &apos;00000000-0000-0000-0000-000000000000&apos;
        ///
        ///SELECT 
        ///		 ess.Id
        ///		,ess.EMP_Info_Id
        ///		,emp.FullName
        ///		,desg.DesignationName
        ///		,ess.TotalEarningAmt
        ///		,ess.TotalDeductionAmt
        ///		,ess.MS_PayMode_Id
        ///	FROM EMP_SLSetup AS ess
        ///		INNER JOIN EMP_Info AS emp ON ess.EMP_Info_Id = emp.Id
        ///		INNER JOIN MS_Designation AS desg ON emp.MS_Designation_Id = desg.Id
        ///	WHERE ess.Active = 1
        ///		AND ess.CompId = @compId
        ///		AND ess.IsAmmend = 0.
        /// </summary>
        internal static string GetSalarySetupByCompId {
            get {
                return ResourceManager.GetString("GetSalarySetupByCompId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///----GetUnSetupSalaryEmployeesByDesignationId.Sql
        ///
        ///
        ///--DECLARE @designationId INT = 1;
        ///--DECLARE @compId UNIQUEIDENTIFIER = &apos;00000000-0000-0000-0000-000000000000&apos;
        ///
        ///select 
        ///	empInfo.Id AS &apos;EmpId&apos;,
        ///	empInfo.FullName
        ///	from EMP_Info AS empInfo
        ///		INNER JOIN MS_Designation AS desg ON desg.Id = empInfo.MS_Designation_Id
        ///		LEFT JOIN EMP_SLSetup AS empSLSetup ON empSLSetup.EMP_Info_Id = empInfo.Id
        ///			AND empInfo.IsActive = 1
        ///	where empInfo.MS_Designation_Id = @designationId
        ///		AND empInfo.CompId = @ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetUnSetupSalaryEmployeesByDesignationId {
            get {
                return ResourceManager.GetString("GetUnSetupSalaryEmployeesByDesignationId", resourceCulture);
            }
        }
    }
}
