//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerModel.SqlAccess.MasterSetup {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MasterSetupSqls {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MasterSetupSqls() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServerModel.SqlAccess.MasterSetup.MasterSetupSqls", typeof(MasterSetupSqls).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///
        ///--CompanyRegistration.Sql
        ///
        ///
        ///
        ///DECLARE @Id uniqueidentifier = &apos;B1D753C9-8A22-4390-960E-2E16ED3EE896&apos;;
        ///DECLARE @FormDate datetime = &apos;&apos;;
        ///DECLARE @MachineId nvarchar(50) = &apos;&apos;;
        ///DECLARE @MachineIp nvarchar(50) = &apos;&apos;;
        ///DECLARE @CompanyName nvarchar(max) = &apos;&apos;;
        ///DECLARE @CompanyDomain nvarchar(max) = &apos;&apos;;
        ///DECLARE @CompanyAddress nvarchar(max) = &apos;address&apos;;
        ///DECLARE @MS_Country_Id int = 0;
        ///DECLARE @MS_State_Id int = 0;
        ///DECLARE @MS_City_Id int = 0;
        ///DECLARE @Pincode nvarchar(10) = &apos;&apos;;
        ///DECLARE @PFNo nvarch [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CompanyRegistration {
            get {
                return ResourceManager.GetString("CompanyRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ////*
        ///---GetAssetDetailsByCompId.Sql
        ///
        ///DECLARE @CompId UNIQUEIDENTIFIER = &apos;D33691FC-7EB9-4D1C-888C-4F4B6E204680&apos;;
        ///*/
        ///
        ///SELECT Id
        ///      ,CompId
        ///      ,AssetName
        ///	  ,IsSubmitToBack
        ///      ,Active
        ///  FROM MS_Asset
        ///  WHERE CompId = @CompId.
        /// </summary>
        internal static string GetAssetsByCompId {
            get {
                return ResourceManager.GetString("GetAssetsByCompId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///--Sql.GetBankBranchesByBankIdAndCompId
        ///
        ////*
        ///DECLARE @compId UNIQUEIDENTIFIER = &apos;00000000-0000-0000-0000-000000000000&apos;
        ///DECLARE @bankId INT = 1
        ///
        ///*/
        ///
        ///SELECT BB.Id
        ///      ,BB.FormDate
        ///      ,BB.CompId
        ///      ,BB.MS_Bank_Id
        ///	  ,B.BankName
        ///      ,BB.BranchName
        ///      ,BB.BranchAddress
        ///      ,BB.BrachCode
        ///      ,BB.IFSC
        ///      ,BB.MICR
        ///      ,BB.BranchContact
        ///  FROM MS_Bank_Branch as BB
        ///	INNER JOIN MS_Bank AS b ON b.Id = BB.MS_Bank_Id
        ///  WHERE BB.MS_Bank_Id = @bankId
        ///	AND BB.CompId = @compId.
        /// </summary>
        internal static string GetBankBranchesByBankIdAndCompId {
            get {
                return ResourceManager.GetString("GetBankBranchesByBankIdAndCompId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///--Sql.GetBankBranchesByCompId
        ////*
        ///DECLARE @compId UNIQUEIDENTIFIER = &apos;00000000-0000-0000-0000-000000000000&apos;
        ///
        ///*/
        ///
        ///SELECT BB.Id
        ///      ,BB.FormDate
        ///      ,BB.CompId
        ///      ,BB.MS_Bank_Id
        ///	  ,B.BankName
        ///      ,BB.BranchName
        ///      ,BB.BranchAddress
        ///      ,BB.BrachCode
        ///      ,BB.IFSC
        ///      ,BB.MICR
        ///      ,BB.BranchContact
        ///  FROM MS_Bank_Branch as BB
        ///	INNER JOIN MS_Bank AS b ON b.Id = BB.MS_Bank_Id
        ///  WHERE BB.CompId = @compId.
        /// </summary>
        internal static string GetBankBranchesByCompId {
            get {
                return ResourceManager.GetString("GetBankBranchesByCompId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ////*
        ///---GetBanksDetails
        ///
        ///DECLARE @CompId UNIQUEIDENTIFIER = &apos;D33691FC-7EB9-4D1C-888C-4F4B6E204680&apos;;
        ///*/
        ///
        ///SELECT Id
        ///      ,CompId
        ///      ,BankName
        ///      ,Active
        ///  FROM MS_Bank
        ///  WHERE CompId = @CompId.
        /// </summary>
        internal static string GetBanksDetails {
            get {
                return ResourceManager.GetString("GetBanksDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ////*
        ///---GetCitiesByStateId
        ///
        ///DECLARE @stateId int = 1;
        ///
        ///*/
        ///
        ///SELECT c1.Id
        ///	  ,c1.CityName
        ///	  ,c1.CityCode
        ///	  ,c1.MS_States_Id
        ///	  ,s.StateName
        ///	  ,s.StateCode
        ///	  ,c1.MS_Country_id
        ///      ,c.CountryName
        ///      ,CountryCode
        ///  FROM MS_Cities as c1
        ///	INNER JOIN MS_Country as c on c.Id = c1.MS_Country_Id
        ///	INNER JOIN MS_States as s on s.Id = c1.MS_States_Id
        ///  WHERE c1.MS_States_Id = @stateId.
        /// </summary>
        internal static string GetCitiesByStateId {
            get {
                return ResourceManager.GetString("GetCitiesByStateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ////*
        ///
        ///--GetCompanyRegistrationDetails.Sql
        ///
        ///
        ///
        ///*/
        ///
        ///SELECT Id
        ///      ,FormDate
        ///      ,MachineId
        ///      ,MachineIp
        ///      ,CompanyName
        ///      ,CompanyDomain
        ///      ,CompanyAddress
        ///      ,MS_Country_Id
        ///      ,MS_State_Id
        ///      ,MS_City_Id
        ///      ,Pincode
        ///      ,PFNo
        ///      ,TANNo
        ///      ,PANNo
        ///      ,ESINo
        ///      ,LINNo
        ///      ,GSTNo
        ///      ,FinancialYearFrom
        ///      ,FinancialYearTo
        ///      ,RegCertNo
        ///	  ,IndustryType_Id
        ///	  ,Website
        ///	  ,Timezone_Id
        ///      ,ReportingCnt
        ///      ,ReportingCntMail
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetCompanyRegistrationDetails {
            get {
                return ResourceManager.GetString("GetCompanyRegistrationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ////*
        ///
        ///--GetCompanyRegistrationDetailsById.Sql
        ///
        ///
        ///
        ///DECLARE @Id UNIQUEIDENTIFIER = &apos;D33691FC-7EB9-4D1C-888C-4F4B6E204680&apos;
        ///*/
        ///
        ///SELECT Id
        ///      ,FormDate
        ///      ,MachineId
        ///      ,MachineIp
        ///      ,CompanyName
        ///      ,CompanyDomain
        ///      ,CompanyAddress
        ///      ,MS_Country_Id
        ///      ,MS_State_Id
        ///      ,MS_City_Id
        ///      ,Pincode
        ///      ,PFNo
        ///      ,TANNo
        ///      ,PANNo
        ///      ,ESINo
        ///      ,LINNo
        ///      ,GSTNo
        ///      ,FinancialYearFrom
        ///      ,FinancialYearTo
        ///      ,RegCertNo
        ///	  ,IndustryType_Id
        ///	  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetCompanyRegistrationDetailsById {
            get {
                return ResourceManager.GetString("GetCompanyRegistrationDetailsById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ////*
        ///---GetCompDocsByCompId.Sql
        ///
        ///DECLARE @CompId UNIQUEIDENTIFIER = &apos;00000000-0000-0000-0000-000000000000&apos;;
        ///*/
        ///
        ///SELECT Id
        ///	  ,FormDate
        ///      ,CompId
        ///      ,DocumentName
        ///	  ,DocumentPath
        ///      ,Active
        ///  FROM MS_CompDocs
        ///  WHERE CompId = @CompId.
        /// </summary>
        internal static string GetCompDocsByCompId {
            get {
                return ResourceManager.GetString("GetCompDocsByCompId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ////*
        ///---GetCompPlanDetailsByCompId.Sql
        ///
        ///DECLARE @CompId UNIQUEIDENTIFIER = &apos;00000000-0000-0000-0000-000000000000&apos;;
        ///*/
        ///
        ///SELECT Id
        ///	  ,FormDate
        ///      ,CompId
        ///      ,MS_Module_Id
        ///	  ,ActiveFrom
        ///	  ,ActiveTo
        ///      ,Active
        ///  FROM MS_CompPlan
        ///  WHERE CompId = @CompId.
        /// </summary>
        internal static string GetCompPlanDetailsByCompId {
            get {
                return ResourceManager.GetString("GetCompPlanDetailsByCompId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ////*
        ///
        ///
        ///---GetCountries
        ///
        ///
        ///*/
        ///
        ///
        ///
        ///SELECT Id
        ///      ,CountryName
        ///      ,CountryCode
        ///  FROM MS_Country.
        /// </summary>
        internal static string GetCountries {
            get {
                return ResourceManager.GetString("GetCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ////*
        ///
        ///---GetDepatmentDetailsByCompId
        ///
        ///DECLARE @CompId uniqueidentifier = &apos;00000000-0000-0000-0000-000000000000&apos;;
        ///
        ///*/
        ///
        ///
        ///SELECT dept.Id
        ///      ,dept.MachineId
        ///      ,dept.MachineIp
        ///      ,dept.CompId
        ///      ,dept.DepartmentName
        ///      ,dept.DepartmentCode
        ///      ,dept.DepartmentShortName
        ///      ,dept.MailAlias
        ///      ,dept.DepartmentLead_Id
        ///	  ,emp.FullName AS DepartmentLeadName
        ///      ,dept.ParentDepartment_Id
        ///	  ,parentDept.DepartmentName AS ParentDepartmentName
        ///      ,dept.CreatedOn
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetDepartmentDetailsByCompId {
            get {
                return ResourceManager.GetString("GetDepartmentDetailsByCompId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ////*
        ///--GetDesignationsByCompId
        ///
        ///DECLARE @CompId uniqueidentifier = &apos;D33691FC-7EB9-4D1C-888C-4F4B6E204680&apos;
        ///
        ///*/
        ///
        ///SELECT Id
        ///      ,MachineId
        ///      ,MachineIp
        ///      ,CompId
        ///      ,DesignationName
        ///      ,DesignationCode
        ///      ,DesignationShortName
        ///      ,Active
        ///  FROM MS_Designation
        ///  WHERE CompId = @compId.
        /// </summary>
        internal static string GetDesignationsByCompId {
            get {
                return ResourceManager.GetString("GetDesignationsByCompId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ////*
        ///---GetInterviewRatings
        ///
        ///DECLARE @compId UNIQUEIDENTIFIER = &apos;D33691FC-7EB9-4D1C-888C-4F4B6E204680&apos;;
        ///*/
        ///
        ///SELECT Id
        ///      ,CompId
        ///      ,InterviewRate
        ///      ,Active
        ///  FROM MS_InterviewRate
        ///  WHERE CompId = @compId
        ///	AND Active = 1.
        /// </summary>
        internal static string GetInterviewRating {
            get {
                return ResourceManager.GetString("GetInterviewRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ////*
        ///--- GetLeaveDetails.Sql
        ///
        ///DECLARE @CompId UNIQUEIDENTIFIER = &apos;D33691FC-7EB9-4D1C-888C-4F4B6E204680&apos; 
        ///
        ///*/
        ///
        ///SELECT Id
        ///      ,CompId
        ///      ,LeaveName
        ///      ,LeaveCode
        ///      ,LeaveType
        ///      ,Unit
        ///      ,EffectiveAfterOnTypes
        ///      ,CarryForward
        ///      ,ApplicableFor
        ///      ,MS_Branch_Id
        ///      ,DurationAllowed
        ///      ,Active
        ///  FROM MS_Leave
        ///  WHERE CompId = @CompId.
        /// </summary>
        internal static string GetLeaveDetails {
            get {
                return ResourceManager.GetString("GetLeaveDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ////*
        ///DECLARE @CompId UNIQUEIDENTIFIER = &apos;00000000-0000-0000-0000-000000000000&apos;
        ///
        ///*/
        ///
        ///SELECT ln.Id
        ///      ,ln.CompId
        ///      ,ln.LNTypeName
        ///      ,ln.InterestRate
        ///      ,ln.IsMaxAmtManual
        ///      ,ln.MaxAmount
        ///      ,ln.MS_SLHead_Id
        ///	  ,sl.SalaryHeadName
        ///      ,ln.Percentage
        ///      ,ln.TenureMonths
        ///      ,ln.AllowPartialPay
        ///  FROM MS_LN AS ln
        ///	LEFT JOIN MS_SLHeads AS sl ON ln.MS_SLHead_Id = sl.Id
        ///  WHERE ln.CompId = @CompId.
        /// </summary>
        internal static string GetLoanTypesByCompId {
            get {
                return ResourceManager.GetString("GetLoanTypesByCompId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ////*
        ///--GetLocationDetails.Sql
        ///
        ///DECLARE @Id int = 2
        ///
        ///*/
        ///
        ///SELECT Id
        ///      ,MachineId
        ///      ,MachineIp
        ///      ,CompId
        ///      ,BranchName
        ///      ,MailAlias
        ///      ,TimeZone_Id
        ///      ,BranchCode
        ///      ,BranchAddress
        ///      ,CountryId
        ///      ,StateId
        ///      ,CityId
        ///      ,PostalCode
        ///      ,IsMainBranch
        ///      ,BranchHead_Id
        ///      ,CreatedOn
        ///      ,CreatedBy
        ///      ,ModifiedOn
        ///      ,ModifiedBy
        ///      ,Active
        ///  FROM MS_Branch
        ///	WHERE Id = @Id
        ///.
        /// </summary>
        internal static string GetLocationDetails {
            get {
                return ResourceManager.GetString("GetLocationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ////*
        ///--GetLocationDetails.Sql
        ///
        ///DECLARE @CompId uniqueidentifier = &apos;D33691FC-7EB9-4D1C-888C-4F4B6E204680&apos;
        ///
        ///*/
        ///
        ///SELECT Id
        ///      ,MachineId
        ///      ,MachineIp
        ///      ,CompId
        ///      ,BranchName
        ///      ,MailAlias
        ///      ,TimeZone_Id
        ///      ,BranchCode
        ///      ,BranchAddress
        ///      ,CountryId
        ///      ,StateId
        ///      ,CityId
        ///      ,PostalCode
        ///      ,IsMainBranch
        ///      ,BranchHead_Id
        ///      ,CreatedOn
        ///      ,CreatedBy
        ///      ,ModifiedOn
        ///      ,ModifiedBy
        ///      ,Active
        ///  FROM MS_Branch
        ///	WHERE CompId = @ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetLocationDetailsByCompId {
            get {
                return ResourceManager.GetString("GetLocationDetailsByCompId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ////**
        ///
        ///---GetMastersDocsTemplates.sql
        ///
        ///DECLARE @CompId uniqueidentifier = &apos;D33691FC-7EB9-4D1C-888C-4F4B6E204680&apos;;
        ///
        ///**/
        ///
        ///SELECT Id
        ///	  ,CompId
        ///	  ,DocName
        ///	  ,DocPath
        ///  FROM MS_DocList
        ///  WHERE CompId = @CompId.
        /// </summary>
        internal static string GetMastersDocsTemplates {
            get {
                return ResourceManager.GetString("GetMastersDocsTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ////**
        ///
        ///---GetMastersDocTemplateById.sql
        ///
        ///DECLARE @documentId INT = 1;
        ///
        ///**/
        ///
        ///SELECT Id
        ///	  ,CompId
        ///	  ,DocName
        ///	  ,DocPath
        ///  FROM MS_DocList
        ///  WHERE Id = @documentId.
        /// </summary>
        internal static string GetMastersDocTemplateById {
            get {
                return ResourceManager.GetString("GetMastersDocTemplateById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ////*
        ///
        ///
        ///---GetPayrollAdjustmentTypesByCompId.Sql
        ///
        ///DECLARE @compId UNIQUEIDENTIFIER = &apos;C225A53F-9ECB-4B9A-88DC-EAEF6115C2A4&apos;
        ///
        ///*/
        ///
        ///
        ///
        ///SELECT
        ///	 ad.Id
        ///	,ad.CompId
        ///	,ad.IsEarningHead
        ///	,ad.AdjustmentType
        ///	,ad.PercentageAmt
        ///	,ad.IsRuleBased
        ///	,ad.MS_SLHeads_Id
        ///	,sl.SalaryHeadName
        ///	FROM MS_Payroll_AdjustType AS ad
        ///		LEFT JOIN MS_SLHeads AS sl ON sl.Id = ad.MS_SLHeads_Id
        ///		WHERE ad.CompId = @compId.
        /// </summary>
        internal static string GetPayrollAdjustmentTypesByCompId {
            get {
                return ResourceManager.GetString("GetPayrollAdjustmentTypesByCompId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ////*
        ///---GetReimbursementTypesByCompId
        ///
        ///DECLARE @CompId UNIQUEIDENTIFIER = &apos;D33691FC-7EB9-4D1C-888C-4F4B6E204680&apos;;
        ///*/
        ///
        ///SELECT a.Id
        ///      ,a.CompId
        ///      ,a.ReimbursementType
        ///      ,a.MonthlyLimit
        ///	  ,a.Frequency
        ///	  ,a.IsDesignationSpecific
        ///	  ,a.MS_Designation_Id
        ///	  ,b.DesignationName
        ///  FROM MS_Reim_Types as a
        ///	LEFT JOIN MS_Designation as b on a.MS_Designation_Id = b.Id
        ///  WHERE a.CompId = @CompId.
        /// </summary>
        internal static string GetReimbursementTypesByCompId {
            get {
                return ResourceManager.GetString("GetReimbursementTypesByCompId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ////*
        ///---GetSalaryHeadsByCompId.Sql
        ///
        ///DECLARE @CompId uniqueidentifier = &apos;D33691FC-7EB9-4D1C-888C-4F4B6E204680&apos;;
        ///
        ///*/
        ///
        ///SELECT sl1.Id
        ///      ,sl1.CompId
        ///      ,sl1.SalaryHeadName
        ///      ,sl1.ShortSalaryHeadName
        ///      ,sl1.IsEarningComponent
        ///      ,sl1.IsFixedComponent
        ///	  ,sl1.IsTaxableComponent
        ///	  ,sl1.IsShowInSalarySlip
        ///	  ,sl1.SalaryHeadOrder
        ///	  ,sl1.MS_SLHeads_Id
        ///	  ,sl2.SalaryHeadName AS &apos;HeadOf&apos;
        ///	  ,sl1.[Percentage]
        ///      ,sl1.Active
        ///  FROM MS_SLHeads AS sl1
        ///	LEFT JOIN MS_SLHeads AS sl2  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetSalaryHeadsByCompId {
            get {
                return ResourceManager.GetString("GetSalaryHeadsByCompId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ////*
        ///
        ///---GetShiftDetailsByBranchIdAndCompId
        ///
        ///
        ///DECLARE @CompId UNIQUEIDENTIFIER = &apos;D33691FC-7EB9-4D1C-888C-4F4B6E204680&apos;;
        ///DECLARE @BranchId INT = 1;
        ///
        ///*/
        ///
        ///SELECT MS_Shift.Id
        ///      ,MS_Shift.CompId
        ///      ,MS_Shift.MS_Branch_Id
        ///      ,MS_Shift.ShiftName
        ///      ,MS_Shift.ShiftCode
        ///      ,MS_Shift.ShiftShortName
        ///      ,MS_Shift.StartTime
        ///      ,MS_Shift.EndTime
        ///      ,MS_Shift.TotalHrs
        ///      ,MS_Shift.WeeklyOffDay
        ///	  ,MS_Shift.IsShiftAllowance
        ///	  ,MS_Shift.ShiftAllowanceAmtPerDay
        ///	  ,MS_Shift [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetShiftDetailsByBranchIdAndCompId {
            get {
                return ResourceManager.GetString("GetShiftDetailsByBranchIdAndCompId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ////*
        ///
        ///---GetShiftDetailsByBranchIdAndCompId
        ///
        ///
        ///DECLARE @CompId UNIQUEIDENTIFIER = &apos;D33691FC-7EB9-4D1C-888C-4F4B6E204680&apos;;
        ///
        ///*/
        ///
        ///SELECT shift.Id
        ///      ,shift.CompId
        ///      ,shift.MS_Branch_Id
        ///	  ,branch.BranchName
        ///      ,shift.ShiftName
        ///      ,shift.ShiftCode
        ///      ,shift.ShiftShortName
        ///      ,shift.StartTime
        ///      ,shift.EndTime
        ///      ,shift.TotalHrs
        ///      ,shift.WeeklyOffDay
        ///	  ,shift.IsShiftAllowance
        ///	  ,shift.ShiftAllowanceAmtPerDay
        ///	  ,shift.IsOTApplicable
        ///	  ,shift.OTAmtPerHrs
        ///	  , [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetShiftDetailsByCompId {
            get {
                return ResourceManager.GetString("GetShiftDetailsByCompId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ////*
        ///---GetStatesByCountryId
        ///
        ///DECLARE @countryId int = 1;
        ///*/
        ///
        ///SELECT s.Id
        ///	  ,s.StateName
        ///	  ,s.StateCode
        ///	  ,s.MS_Country_Id
        ///      ,c.CountryName
        ///      ,CountryCode
        ///  FROM MS_States as s
        ///	INNER JOIN MS_Country as c on c.Id = s.MS_Country_Id
        ///  WHERE s.MS_Country_Id = @countryId.
        /// </summary>
        internal static string GetStatesByCountryId {
            get {
                return ResourceManager.GetString("GetStatesByCountryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ////*
        ///---GetTicketCategoriesByCompId.Sql
        ///
        ///DECLARE @compId uniqueidentifier = &apos;00000000-0000-0000-0000-000000000000&apos;;
        ///*/
        ///
        ///SELECT s.Id
        ///	  ,s.FormDate
        ///	  ,s.CompId
        ///	  ,s.TicketCategory
        ///  FROM MS_TicketCat as s
        ///  WHERE s.CompId = @compId.
        /// </summary>
        internal static string GetTicketCategoriesByCompId {
            get {
                return ResourceManager.GetString("GetTicketCategoriesByCompId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ////*
        ///---GetTrainingsByCompId
        ///
        ///DECLARE @CompId UNIQUEIDENTIFIER = &apos;D33691FC-7EB9-4D1C-888C-4F4B6E204680&apos;;
        ///*/
        ///
        ///SELECT training.Id
        ///      ,training.CompId
        ///      ,training.TrainingName
        ///      ,training.TrainingShortName
        ///      ,training.Description
        ///      ,training.IsTrainingMandatory
        ///      ,training.MS_Designation_Id
        ///	  ,desig.DesignationName
        ///  FROM MS_Training as training
        ///	INNER JOIN MS_Designation as desig ON desig.Id = training.MS_Designation_Id
        ///	WHERE training.CompId = @CompId.
        /// </summary>
        internal static string GetTrainingsByCompId {
            get {
                return ResourceManager.GetString("GetTrainingsByCompId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ////*
        ///---GetTrainingsByCompId
        ///
        ///DECLARE @CompId UNIQUEIDENTIFIER = &apos;D33691FC-7EB9-4D1C-888C-4F4B6E204680&apos;;
        ///DECLARE @designationId INT = 10;
        ///*/
        ///
        ///SELECT training.Id
        ///      ,training.CompId
        ///      ,training.TrainingName
        ///      ,training.TrainingShortName
        ///      ,training.Description
        ///      ,training.IsTrainingMandatory
        ///      ,training.MS_Designation_Id
        ///	  ,desig.DesignationName
        ///  FROM MS_Training as training
        ///	INNER JOIN MS_Designation as desig ON desig.Id = training.MS_Designation_Id
        ///	WHERE train [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetTrainingsByDesignationIdAndCompId {
            get {
                return ResourceManager.GetString("GetTrainingsByDesignationIdAndCompId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ////*
        ///--UpsertAsset.Sql
        ///
        ///--select * from MS_Asset
        ///
        ///DECLARE @Id int = 1;
        ///DECLARE @CompId uniqueidentifier = &apos;D33691FC-7EB9-4D1C-888C-4F4B6E204680&apos;;
        ///DECLARE @AssetName nvarchar(MAX) = &apos;name23&apos;;
        ///DECLARE @IsSubmitToBack bit = 1;
        ///DECLARE @Active bit = 1;
        ///
        ///*/
        ///
        ///MERGE INTO MS_Asset as Target
        ///USING (select @Id as Id, @AssetName as AssetName) AS source
        ///    ON (Target.Id = source.Id) 
        ///
        ///WHEN MATCHED THEN
        ///	UPDATE SET
        ///		 AssetName = @AssetName
        ///		,IsSubmitToBack = @IsSubmitToBack
        ///		,[Active] = @Active        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpsertAsset {
            get {
                return ResourceManager.GetString("UpsertAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ////*
        ///--UpsertBank.Sql
        ///
        ///--select * from MS_Bank
        ///
        ///DECLARE @Id int = 1;
        ///DECLARE @CompId uniqueidentifier = &apos;D33691FC-7EB9-4D1C-888C-4F4B6E204680&apos;;
        ///DECLARE @BankName nvarchar(255) = &apos;name23&apos;;
        ///DECLARE @Active bit = 1;
        ///
        ///
        ///
        ///*/
        ///
        ///MERGE INTO MS_Bank as Target
        ///USING (select @Id as Id, @BankName as BankName) AS source
        ///    ON (Target.Id = source.Id) 
        ///
        ///WHEN MATCHED THEN
        ///	UPDATE SET
        ///		 CompId = @CompId
        ///		,BankName = @BankName
        ///		,[Active] = @Active
        ///
        ///
        ///WHEN NOT MATCHED THEN
        ///        INSERT (
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpsertBank {
            get {
                return ResourceManager.GetString("UpsertBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ////*
        ///--UpsertBank.Sql
        ///
        ///--select * from MS_Bank_Branch
        ///
        ///DECLARE @Id int = 1;
        ///DECLARE @MS_Bank_Id int = 1;
        ///DECLARE @CompId uniqueidentifier = &apos;D33691FC-7EB9-4D1C-888C-4F4B6E204680&apos;;
        ///DECLARE @BranchName nvarchar(max) = &apos;name23&apos;;
        ///DECLARE @BranchAddress nvarchar(max) = &apos;address&apos;;
        ///DECLARE @BrachCode nvarchar(50) = &apos;code&apos;;
        ///DECLARE @IFSC nvarchar(50) = &apos;IFSC&apos;;
        ///DECLARE @MICR nvarchar(50) = &apos;MICR&apos;
        ///DECLARE @BranchContact nvarchar(max) = &apos;address&apos;;
        ///
        ///
        ///
        ///*/
        ///
        ///MERGE INTO MS_Bank_Branch as Target
        ///USING (s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpsertBankBranch {
            get {
                return ResourceManager.GetString("UpsertBankBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ////*
        ///--CreateBranch.Sql
        ///
        ///--select * from MS_Branch
        ///
        ///DECLARE @Id int = 2;
        ///DECLARE @MachineId nvarchar(50) = &apos;&apos;;
        ///DECLARE @MachineIp nvarchar(50) = &apos;&apos;;
        ///DECLARE @CompId uniqueidentifier = &apos;00000000-0000-0000-0000-000000000000&apos;;
        ///DECLARE @BranchName nvarchar(255) = &apos;name2&apos;;
        ///DECLARE @MailAlias nvarchar(250) = &apos;&apos;;
        ///DECLARE @TimeZone_Id int = 0;
        ///DECLARE @BranchCode nvarchar(50) = &apos;&apos;;
        ///DECLARE @BranchAddress nvarchar(max) = &apos;&apos;;
        ///DECLARE @CountryId int = 0;
        ///DECLARE @StateId int = 0;
        ///DECLARE @CityId int =  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpsertBranch {
            get {
                return ResourceManager.GetString("UpsertBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ////*
        ///--UpsertCompanyDocument.Sql
        ///
        ///--select * from MS_CompDocs
        ///
        ///DECLARE @Id int = 0;
        ///DECLARE @CompId uniqueidentifier = &apos;00000000-0000-0000-0000-000000000000&apos;;
        ///DECLARE @DocumentName nvarchar(MAX) = &apos;name23&apos;;
        ///DECLARE @DocumentPath nvarchar(MAX) = &apos;name23&apos;;
        ///DECLARE @Active bit = 1;
        ///
        ///*/
        ///
        ///MERGE INTO MS_CompDocs as Target
        ///USING (select @Id as Id, @DocumentName as DocumentName) AS source
        ///    ON (Target.Id = source.Id) 
        ///
        ///WHEN MATCHED THEN
        ///	UPDATE SET
        ///		 DocumentName = @DocumentName
        ///		,DocumentPa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpsertCompanyDocument {
            get {
                return ResourceManager.GetString("UpsertCompanyDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ////*
        ///--UpsertCompanyPlanDetail.Sql
        ///
        ///--select * from MS_CompPlan
        ///
        ///DECLARE @Id int = 0;
        ///DECLARE @CompId uniqueidentifier = &apos;00000000-0000-0000-0000-000000000000&apos;;
        ///DECLARE @MS_Module_Id int = 0;
        ///DECLARE @ActiveFrom DATETIME() = GETDATE();
        ///DECLARE @ActiveTo DATETIME() = GETDATE();
        ///DECLARE @NosOfUser int = 0;
        ///DECLARE @Active bit = 1;
        ///
        ///*/
        ///
        ///MERGE INTO MS_CompPlan as Target
        ///USING (select @Id as Id, @AssetName as AssetName) AS source
        ///    ON (Target.Id = source.Id) 
        ///
        ///WHEN MATCHED THEN
        ///	UPDATE SET        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpsertCompanyPlanDetail {
            get {
                return ResourceManager.GetString("UpsertCompanyPlanDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ////*
        ///--CreateDepartment.Sql
        ///
        ///--select * from MS_Dept
        ///
        ///DECLARE @Id int = 0;
        ///DECLARE @MachineId nvarchar(50) = &apos;&apos;;
        ///DECLARE @MachineIp nvarchar(50) = &apos;&apos;;
        ///DECLARE @CompId uniqueidentifier = &apos;00000000-0000-0000-0000-000000000000&apos;;
        ///DECLARE @DepartmentName nvarchar(255) = &apos;name2&apos;;
        ///DECLARE @DepartmentCode nvarchar(50) = &apos;name2&apos;;
        ///DECLARE @DepartmentShortName nvarchar(50) = &apos;name2&apos;;
        ///DECLARE @MailAlias nvarchar(255) = &apos;&apos;;
        ///DECLARE @DepartmentLead_Id uniqueidentifier = &apos;00000000-0000-0000-0000-00000000000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpsertDepartment {
            get {
                return ResourceManager.GetString("UpsertDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ////*
        ///--CreateDesignation.Sql
        ///
        ///--select * from MS_Designation
        ///
        ///DECLARE @Id int = 0;
        ///DECLARE @MachineId nvarchar(50) = &apos;&apos;;
        ///DECLARE @MachineIp nvarchar(50) = &apos;&apos;;
        ///DECLARE @CompId uniqueidentifier = &apos;00000000-0000-0000-0000-000000000000&apos;;
        ///DECLARE @DesignationName nvarchar(255) = &apos;name2&apos;;
        ///DECLARE @DesignationCode nvarchar(50) = &apos;name2&apos;;
        ///DECLARE @DesignationShortName nvarchar(50) = &apos;name2&apos;;
        ///DECLARE @Active bit = 1;
        ///
        ///
        ///*/
        ///
        ///
        ///MERGE INTO MS_Designation as Target
        ///USING (select @Id as Id, @DesignationN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpsertDesignation {
            get {
                return ResourceManager.GetString("UpsertDesignation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///--UpsertInterviewRating.Sql
        ///
        ////*
        ///DECLARE @Id int = 7;
        ///DECLARE @compId uniqueidentifier = &apos;00000000-0000-0000-0000-000000000000&apos;;
        ///DECLARE @InterviewRate nvarchar(max) = &apos;name27&apos;;
        ///DECLARE @Active bit = 1;
        ///
        ///*/
        ///
        ///
        ///MERGE INTO MS_InterviewRate as Target
        ///USING (select @Id as Id, @InterviewRate as InterviewRate) AS source
        ///    ON (Target.Id = source.Id) 
        ///
        ///WHEN MATCHED THEN
        ///	UPDATE SET 
        ///		 InterviewRate = @InterviewRate
        ///		,[Active] = @Active
        ///
        ///
        ///WHEN NOT MATCHED THEN
        ///        INSERT (
        ///             [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpsertInterviewRating {
            get {
                return ResourceManager.GetString("UpsertInterviewRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ////*
        ///
        ///--UpsertLeave.Sql
        ///
        ///--select * from MS_Leave
        ///
        ///DECLARE @Id int = 1;
        ///DECLARE @CompId uniqueidentifier = &apos;D33691FC-7EB9-4D1C-888C-4F4B6E204680&apos;;
        ///DECLARE @LeaveName nvarchar(255) = &apos;name23&apos;;
        ///DECLARE @LeaveCode nvarchar(50) = &apos;name23&apos;;
        ///DECLARE @LeaveType nvarchar(50) = &apos;AA&apos;;
        ///DECLARE @Unit nvarchar(50) = &apos;22&apos;;
        ///DECLARE @EffectiveAfterOnTypes int = 1;
        ///DECLARE @CarryForward int = 2;
        ///DECLARE @ApplicableFor nvarchar(50) = &apos;M&apos;;
        ///DECLARE @MS_Branch_Id int = 2;
        ///DECLARE @DurationAllowed nvarchar(50) =  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpsertLeave {
            get {
                return ResourceManager.GetString("UpsertLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///--UpsetLoanTypes.Sql
        ////*
        ///--select * from MS_LN
        ///
        ///DECLARE @Id int = 0;
        ///DECLARE @CompId uniqueidentifier = &apos;00000000-0000-0000-0000-000000000000&apos;;
        ///DECLARE @LNTypeName nvarchar(255) = &apos;name2&apos;;
        ///DECLARE @InterestRate DECIMAL(18, 4) = 10;
        ///DECLARE @IsMaxAmtManual BIT = 1;
        ///DECLARE @MaxAmount DECIMAL(18, 4) = 100;
        ///DECLARE @MS_SLHead_Id INT = 1;
        ///DECLARE @Percentage DECIMAL(18, 4) = 0;
        ///DECLARE @TenureMonths DECIMAL(18, 0) = 12;
        ///DECLARE @AllowPartialPay BIT = 1;
        ///
        ///**/
        ///
        ///
        ///
        ///MERGE INTO MS_LN as Target
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpsertLoanType {
            get {
                return ResourceManager.GetString("UpsertLoanType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///
        ///--UpsertMasterDocTemplate.Sql
        ///
        ///--select * from MS_DocList
        ////*
        ///DECLARE @Id int = 1;
        ///DECLARE @CompId uniqueidentifier = &apos;D33691FC-7EB9-4D1C-888C-4F4B6E204680&apos;;
        ///DECLARE @DocName nvarchar(MAX) = &apos;name23&apos;;
        ///DECLARE @DocPath nvarchar(MAX) = &apos;name23&apos;;
        ///
        ///**/
        ///
        ///MERGE INTO MS_DocList as Target
        ///USING (select @Id as Id, @DocName as DocName) AS source
        ///    ON (Target.Id = source.Id) 
        ///
        ///WHEN MATCHED THEN
        ///	UPDATE SET
        ///		 DocName = @DocName 
        ///		,DocPath = @DocPath
        ///
        ///WHEN NOT MATCHED THEN
        ///        INSERT  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpsertMasterDocTemplate {
            get {
                return ResourceManager.GetString("UpsertMasterDocTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- ========================================
        ///-- Example: Upsert into MS_Payroll_AdjustType
        ///-- ========================================
        ///
        ///--- UpsertPayrollAdjustmentType.sql
        ///
        /// --DECLARE @Id INT = 2;
        /// --DECLARE @CompId UNIQUEIDENTIFIER = &apos;C225A53F-9ECB-4B9A-88DC-EAEF6115C2A4&apos;
        /// --DECLARE @IsEarningHead BIT = 1;
        /// --DECLARE @AdjustmentType NVARCHAR(100) = &apos;Arrears&apos;;
        /// --DECLARE @PercentageAmt DECIMAL(18, 2) = 5;
        /// --DECLARE @MS_SLHeads_Id INT = 1;
        /// --DECLARE @IsRuleBased BIT = 1;
        ///
        /// 
        ///-- MERGE to insert [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpsertPayrollAdjustmentType {
            get {
                return ResourceManager.GetString("UpsertPayrollAdjustmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ////*
        ///--UpsertReimbursementTypes.Sql
        ///
        ///--select * from MS_Reim_Types
        ///
        ///DECLARE @Id int = 1;
        ///DECLARE @CompId uniqueidentifier = &apos;D33691FC-7EB9-4D1C-888C-4F4B6E204680&apos;;
        ///DECLARE @ReimbursementType nvarchar(MAX) = &apos;name23&apos;;
        ///DECLARE @MonthlyLimit DECIMAL(18,4)= 1;
        ///DECLARE @Frequency nvarchar(50) = &apos;Monthly&apos;;
        ///DECLARE @IsDesignationSpecific BIT = 1;
        ///DECLARE @MS_Designation_Id INT = 1;
        ///
        ///*/
        ///
        ///MERGE INTO MS_Reim_Types as Target
        ///USING (select @Id as Id, @ReimbursementType as ReimbursementType) AS source
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpsertReimbursementTypes {
            get {
                return ResourceManager.GetString("UpsertReimbursementTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ////*
        ///
        ///--UpsertSalaryHeads.Sql
        ///
        ///--select * from MS_Leave
        ///
        ///DECLARE @Id int = 1;
        ///DECLARE @CompId uniqueidentifier = &apos;D33691FC-7EB9-4D1C-888C-4F4B6E204680&apos;;
        ///DECLARE @SalaryHeadName nvarchar(255) = &apos;name23&apos;;
        ///DECLARE @ShortSalaryHeadName nvarchar(50) = &apos;name23&apos;;
        ///DECLARE @IsEarningComponent BIT = 1;
        ///DECLARE @IsFixedComponent BIT = 1;
        ///DECLARE @IsTaxableComponent BIT = 1;
        ///DECLARE @IsShowInSalarySlip BIT = 1;
        ///DECLARE @SalaryHeadOrder BIT =999;
        ///DECLARE @MS_SLHeads_Id INT = 1;
        ///DECLARE @Percentage DECI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpsertSalaryHeads {
            get {
                return ResourceManager.GetString("UpsertSalaryHeads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ////*
        ///
        ///--UpsertShift.Sql
        ///
        ///--select * from MS_Shift
        ///
        ///DECLARE @Id int = 5006;
        ///DECLARE @CompId uniqueidentifier = &apos;00000000-0000-0000-0000-000000000000&apos;;
        ///DECLARE @MS_Branch_Id INT = 1;
        ///DECLARE @ShiftName nvarchar(255) = &apos;name23&apos;;
        ///DECLARE @ShiftCode nvarchar(50) = &apos;name23&apos;;
        ///DECLARE @ShiftShortName nvarchar(50) = &apos;name23&apos;;
        ///DECLARE @StartTime TIME(7) = &apos;09:30:00&apos;;
        ///DECLARE @EndTime TIME(7) = &apos;18:30:00&apos;;
        ///DECLARE @TotalHrs DECIMAL(18,0) = 9;
        ///DECLARE @WeeklyOffDay NVARCHAR(50) = &apos;7,1&apos;;
        ///DECLARE @IsShi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpsertShift {
            get {
                return ResourceManager.GetString("UpsertShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ////*
        ///--UpsertTicketCategory.Sql
        ///
        ///--select * from MS_TicketCat
        ///
        ///DECLARE @Id int = 1;
        ///DECLARE @CompId uniqueidentifier = &apos;00000000-0000-0000-0000-000000000000&apos;;
        ///DECLARE @TicketCategory nvarchar(MAX) = &apos;name23&apos;;
        ///
        ///
        ///*/
        ///
        ///MERGE INTO MS_TicketCat as Target
        ///USING (select @Id as Id, @TicketCategory as TicketCategory) AS source
        ///    ON (Target.Id = source.Id) 
        ///
        ///WHEN MATCHED THEN
        ///	UPDATE SET
        ///		TicketCategory = @TicketCategory
        ///
        ///
        ///WHEN NOT MATCHED THEN
        ///        INSERT (
        ///             CompId
        ///			,Ticket [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpsertTicketCategory {
            get {
                return ResourceManager.GetString("UpsertTicketCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ////*
        ///
        ///--UpsertTraining.Sql
        ///
        ///--select * from MS_Training
        ///
        ///DECLARE @Id int = 1;
        ///DECLARE @CompId uniqueidentifier = &apos;D33691FC-7EB9-4D1C-888C-4F4B6E204680&apos;;
        ///DECLARE @TrainingName nvarchar(MAX) = &apos;name23&apos;;
        ///DECLARE @TrainingShortName nvarchar(50) = &apos;name23&apos;;
        ///DECLARE @Description nvarchar(MAX) = &apos;name23&apos;;
        ///DECLARE @IsTrainingMandatory BIT = 1;
        ///DECLARE @MS_Designation_Id INT = 1;
        ///
        ///
        ///*/
        ///
        ///
        ///MERGE INTO MS_Training as Target
        ///USING (select @Id as Id, @TrainingName as TrainingName) AS source
        ///    ON (Ta [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpsertTraining {
            get {
                return ResourceManager.GetString("UpsertTraining", resourceCulture);
            }
        }
    }
}
