//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerModel.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_GenDocs
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> FormDate { get; set; }
        public string MachineId { get; set; }
        public string MachineIp { get; set; }
        public Nullable<System.Guid> CompId { get; set; }
        public System.Guid Req_JbForm_Id { get; set; }
        public Nullable<decimal> CTC { get; set; }
        public string Status { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<int> ProbationPeriod { get; set; }
        public Nullable<int> NoticePeriod { get; set; }
        public Nullable<System.DateTime> DateOfJoining { get; set; }
        public Nullable<int> MS_Doc_Id { get; set; }
        public string DocPath { get; set; }
        public Nullable<System.DateTime> DocCreatedOn { get; set; }
        public Nullable<System.DateTime> DocModifiedOn { get; set; }
        public Nullable<System.DateTime> DocExperiesOn { get; set; }
        public Nullable<bool> Ammend { get; set; }
    }
}
