//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerModel.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_FamilyInfo
    {
        public System.Guid Id { get; set; }
        public Nullable<System.DateTime> FormDate { get; set; }
        public string MachineId { get; set; }
        public string MachineIp { get; set; }
        public Nullable<System.Guid> CompId { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> EMP_Info_Id { get; set; }
        public string MemberName { get; set; }
        public string Profession { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string BloodGroup { get; set; }
        public string Gender { get; set; }
        public string Nationality { get; set; }
        public Nullable<int> RelationshipId { get; set; }
        public Nullable<bool> IsEarningMember { get; set; }
        public string Remark { get; set; }
        public string Address { get; set; }
        public string Pincode { get; set; }
        public string Mobile { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string City { get; set; }
        public Nullable<int> MS_State_Id { get; set; }
        public Nullable<int> MS_Country_Id { get; set; }
    }
}
