//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerModel.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_Qualification
    {
        public System.Guid Id { get; set; }
        public Nullable<System.DateTime> FormDate { get; set; }
        public string MachineId { get; set; }
        public string MachineIp { get; set; }
        public Nullable<System.Guid> CompId { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> EMP_Info_Id { get; set; }
        public string HighestQualification { get; set; }
        public string UniversityName { get; set; }
        public string CollegeName { get; set; }
        public string MainSubjects { get; set; }
        public string Division { get; set; }
        public Nullable<int> PassingYear { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public string MkshtDocPath { get; set; }
        public string MkshtDocPath1 { get; set; }
        public string MkshtDocPath2 { get; set; }
        public string MkshtDocPath3 { get; set; }
        public string PassingCertPath { get; set; }
    }
}
