//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerModel.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_Info
    {
        public System.Guid Id { get; set; }
        public Nullable<System.DateTime> FormDate { get; set; }
        public string MachineId { get; set; }
        public string MachineIp { get; set; }
        public Nullable<System.Guid> CompId { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public string EmpId { get; set; }
        public string EmpType { get; set; }
        public string TicketNo { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public string Gender { get; set; }
        public string FatherHusbandName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> DateOfJoining { get; set; }
        public Nullable<decimal> ProbationDuration { get; set; }
        public Nullable<System.DateTime> ConfirmationDate { get; set; }
        public Nullable<System.DateTime> DateOfLeaving { get; set; }
        public string PFNo { get; set; }
        public string ESINo { get; set; }
        public string PANNo { get; set; }
        public string AadharNo { get; set; }
        public Nullable<int> MS_Branch_Id { get; set; }
        public Nullable<int> MS_Grade_Id { get; set; }
        public Nullable<int> MS_Dept_Id { get; set; }
        public Nullable<int> MS_Designation_Id { get; set; }
        public string SourceOfHire { get; set; }
        public string PaymentMode { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
