//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerModel.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_OtherInfo
    {
        public System.Guid Id { get; set; }
        public Nullable<System.DateTime> FormDate { get; set; }
        public string MachineId { get; set; }
        public string MachineIp { get; set; }
        public Nullable<System.Guid> CompId { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> MS_EmpInfo_Id { get; set; }
        public Nullable<bool> EmpIsOnContract { get; set; }
        public Nullable<System.DateTime> ContractStartDate { get; set; }
        public Nullable<decimal> Duration { get; set; }
        public Nullable<System.DateTime> ContractEndDate { get; set; }
        public Nullable<bool> IsContractAmend { get; set; }
        public string Remark { get; set; }
        public Nullable<int> WeeklyOffDay { get; set; }
    }
}
