//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerModel.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_OfferSL
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> FormDate { get; set; }
        public string MachineIp { get; set; }
        public string MachineId { get; set; }
        public Nullable<System.Guid> CompId { get; set; }
        public System.Guid Req_JbForm_Id { get; set; }
        public Nullable<int> EMP_GenDocs_Id { get; set; }
        public Nullable<int> MS_SLHeads_Id { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<bool> IsAmmend { get; set; }
    }
}
