//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerModel.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_PersonalInfo
    {
        public System.Guid Id { get; set; }
        public Nullable<System.DateTime> FormDate { get; set; }
        public string MachineId { get; set; }
        public string MachineIp { get; set; }
        public Nullable<System.Guid> CompId { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> EMP_Info_Id { get; set; }
        public string Email { get; set; }
        public string Mobile1 { get; set; }
        public string Mobile2 { get; set; }
        public string MaritialStatus { get; set; }
        public Nullable<System.DateTime> MarrigeDate { get; set; }
        public Nullable<int> NoOfChildren { get; set; }
        public string BirthPlace { get; set; }
        public string Religion { get; set; }
        public string LICNo { get; set; }
        public string PassportNo { get; set; }
        public string VehicleNo { get; set; }
        public string BloodGroup { get; set; }
        public string Hobbies { get; set; }
    }
}
