//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerModel.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_AcctInfo
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> FormDate { get; set; }
        public string MachineId { get; set; }
        public string MachineIp { get; set; }
        public Nullable<System.Guid> CompId { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> EMP_Info_Id { get; set; }
        public Nullable<int> MS_Bank_Id { get; set; }
        public Nullable<int> MS_Bank_Branch_Id { get; set; }
        public string AccountNo { get; set; }
        public Nullable<int> MS_AccountType_Id { get; set; }
        public Nullable<int> MS_PaymentType_Id { get; set; }
        public string DDPayableAt { get; set; }
        public string NameAsPerBank { get; set; }
        public string UAN { get; set; }
        public string PFNo { get; set; }
        public Nullable<bool> IsCoveredESI { get; set; }
        public string ESINo { get; set; }
        public Nullable<bool> IsCoveredLWF { get; set; }
        public Nullable<int> AmendId { get; set; }
        public Nullable<bool> IsAmend { get; set; }
    }
}
