//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerModel.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_Addr
    {
        public System.Guid Id { get; set; }
        public Nullable<System.DateTime> FormDate { get; set; }
        public string MachineId { get; set; }
        public string MachineIp { get; set; }
        public Nullable<System.Guid> CompId { get; set; }
        public Nullable<System.Guid> EMP_Info_Id { get; set; }
        public Nullable<int> AddressTypeId { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string FlatNo { get; set; }
        public string Premise { get; set; }
        public string Road { get; set; }
        public string Area { get; set; }
        public string Town { get; set; }
        public Nullable<int> MS_State_Id { get; set; }
        public Nullable<int> MS_Country_Id { get; set; }
        public string PinCode { get; set; }
        public string FullAddress { get; set; }
        public string AddressProofDoc { get; set; }
        public Nullable<bool> IsSameAsPresentAddress { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
