//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerModel.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_Images
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> FormDate { get; set; }
        public Nullable<System.Guid> CompId { get; set; }
        public Nullable<System.Guid> EMP_Info_Id { get; set; }
        public Nullable<int> MS_ImageType_Id { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
