//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerModel.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_LNReq
    {
        public System.Guid Id { get; set; }
        public Nullable<System.DateTime> FormDate { get; set; }
        public string MachineId { get; set; }
        public string MachineIp { get; set; }
        public Nullable<System.Guid> CompId { get; set; }
        public Nullable<System.Guid> EMP_Info_Id { get; set; }
        public Nullable<int> MS_LN_Id { get; set; }
        public Nullable<decimal> ReqAmt { get; set; }
        public Nullable<decimal> ApprAmt { get; set; }
        public Nullable<decimal> TenureMonths { get; set; }
        public string Status { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> Ammend { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
