//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerModel.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_HelpDeskReplies
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> FormDate { get; set; }
        public Nullable<System.Guid> CompId { get; set; }
        public Nullable<int> HR_HelpDesk_Id { get; set; }
        public Nullable<System.Guid> RepliedByEmpId { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> ReplyDate { get; set; }
    }
}
