//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerModel.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_HelpDesk
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> FormDate { get; set; }
        public Nullable<System.Guid> CompId { get; set; }
        public Nullable<System.Guid> EMP_Info_Id { get; set; }
        public Nullable<int> MS_TicketCat_Id { get; set; }
        public string TicketName { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public Nullable<int> Severity { get; set; }
        public string AttachmentPath { get; set; }
        public Nullable<System.Guid> AssignEmpId { get; set; }
        public string TicketStatus { get; set; }
        public Nullable<System.DateTime> TicketResolvedDt { get; set; }
        public Nullable<bool> IsAmmend { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> AmmendId { get; set; }
    }
}
