//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerModel.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HRMSEntities : DbContext
    {
        public HRMSEntities()
            : base("name=HRMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EMP_Achievements> EMP_Achievements { get; set; }
        public virtual DbSet<EMP_Docs> EMP_Docs { get; set; }
        public virtual DbSet<EMP_EarningMem> EMP_EarningMem { get; set; }
        public virtual DbSet<EMP_OtherInfo> EMP_OtherInfo { get; set; }
        public virtual DbSet<EMP_Shift> EMP_Shift { get; set; }
        public virtual DbSet<EMP_WorkExp> EMP_WorkExp { get; set; }
        public virtual DbSet<EMP_Leaves> EMP_Leaves { get; set; }
        public virtual DbSet<Req_InterviewFedbck> Req_InterviewFedbck { get; set; }
        public virtual DbSet<Req_InterviewSch> Req_InterviewSch { get; set; }
        public virtual DbSet<Req_JbForm> Req_JbForm { get; set; }
        public virtual DbSet<Req_JbVacancy> Req_JbVacancy { get; set; }
        public virtual DbSet<Req_TrainingFedbck> Req_TrainingFedbck { get; set; }
        public virtual DbSet<Req_TrainingSch> Req_TrainingSch { get; set; }
        public virtual DbSet<EMP_FamilyInfo> EMP_FamilyInfo { get; set; }
        public virtual DbSet<EMP_Punch> EMP_Punch { get; set; }
        public virtual DbSet<MS_Bank> MS_Bank { get; set; }
        public virtual DbSet<MS_Branch> MS_Branch { get; set; }
        public virtual DbSet<MS_Cities> MS_Cities { get; set; }
        public virtual DbSet<MS_CompReg> MS_CompReg { get; set; }
        public virtual DbSet<MS_Country> MS_Country { get; set; }
        public virtual DbSet<MS_Dept> MS_Dept { get; set; }
        public virtual DbSet<MS_Designation> MS_Designation { get; set; }
        public virtual DbSet<MS_DocList> MS_DocList { get; set; }
        public virtual DbSet<MS_Leave> MS_Leave { get; set; }
        public virtual DbSet<MS_PayMode> MS_PayMode { get; set; }
        public virtual DbSet<MS_Bank_Branch> MS_Bank_Branch { get; set; }
        public virtual DbSet<EMP_Images> EMP_Images { get; set; }
        public virtual DbSet<MS_ImageType> MS_ImageType { get; set; }
        public virtual DbSet<EMP_AcctInfo> EMP_AcctInfo { get; set; }
        public virtual DbSet<PR_EMP_SL> PR_EMP_SL { get; set; }
        public virtual DbSet<MS_SLHeads> MS_SLHeads { get; set; }
        public virtual DbSet<MS_InterviewRate> MS_InterviewRate { get; set; }
        public virtual DbSet<MS_Training> MS_Training { get; set; }
        public virtual DbSet<MS_Holiday> MS_Holiday { get; set; }
        public virtual DbSet<EMP_Training> EMP_Training { get; set; }
        public virtual DbSet<MS_Asset> MS_Asset { get; set; }
        public virtual DbSet<EMP_SLHeads> EMP_SLHeads { get; set; }
        public virtual DbSet<EMP_SLSetup> EMP_SLSetup { get; set; }
        public virtual DbSet<EMP_LeaveReq> EMP_LeaveReq { get; set; }
        public virtual DbSet<MS_CompDocs> MS_CompDocs { get; set; }
        public virtual DbSet<MS_Shift> MS_Shift { get; set; }
        public virtual DbSet<MS_CompPlan> MS_CompPlan { get; set; }
        public virtual DbSet<PR_CRT> PR_CRT { get; set; }
        public virtual DbSet<MS_LogInOut> MS_LogInOut { get; set; }
        public virtual DbSet<Reim_Appro_Claims> Reim_Appro_Claims { get; set; }
        public virtual DbSet<PR_Reimbursement> PR_Reimbursement { get; set; }
        public virtual DbSet<Reim_Claims> Reim_Claims { get; set; }
        public virtual DbSet<HR_HelpDeskReplies> HR_HelpDeskReplies { get; set; }
        public virtual DbSet<MS_TicketCat> MS_TicketCat { get; set; }
        public virtual DbSet<HR_HelpDesk> HR_HelpDesk { get; set; }
        public virtual DbSet<MS_Reim_Types> MS_Reim_Types { get; set; }
        public virtual DbSet<EMP_Info> EMP_Info { get; set; }
        public virtual DbSet<EMP_PersonalInfo> EMP_PersonalInfo { get; set; }
        public virtual DbSet<EMP_Addr> EMP_Addr { get; set; }
        public virtual DbSet<EMP_Qualification> EMP_Qualification { get; set; }
        public virtual DbSet<EMP_OfferSL> EMP_OfferSL { get; set; }
        public virtual DbSet<EMP_GenDocs> EMP_GenDocs { get; set; }
        public virtual DbSet<MS_LN> MS_LN { get; set; }
        public virtual DbSet<EMP_LNReq> EMP_LNReq { get; set; }
        public virtual DbSet<HR_LNReq> HR_LNReq { get; set; }
        public virtual DbSet<LN_RepPaySch> LN_RepPaySch { get; set; }
        public virtual DbSet<LN_Disb> LN_Disb { get; set; }
        public virtual DbSet<PR_EMP_SL_Adjustment> PR_EMP_SL_Adjustment { get; set; }
        public virtual DbSet<MS_Payroll_AdjustType> MS_Payroll_AdjustType { get; set; }
        public virtual DbSet<EMP_FaceEmbeddings> EMP_FaceEmbeddings { get; set; }
    }
}
