//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerModel.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LN_RepPaySch
    {
        public System.Guid Id { get; set; }
        public Nullable<System.DateTime> FormDate { get; set; }
        public string MachineId { get; set; }
        public string MachineIp { get; set; }
        public Nullable<System.Guid> CompId { get; set; }
        public Nullable<System.Guid> EMP_LNReq_Id { get; set; }
        public Nullable<decimal> InstallmentNo { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<decimal> EMIAmt { get; set; }
        public Nullable<decimal> PrincipalAmt { get; set; }
        public Nullable<decimal> InterestAmt { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public string Status { get; set; }
    }
}
