//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerModel.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MS_Bank_Branch
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> FormDate { get; set; }
        public Nullable<System.Guid> CompId { get; set; }
        public Nullable<int> MS_Bank_Id { get; set; }
        public string BranchName { get; set; }
        public string BranchAddress { get; set; }
        public string BrachCode { get; set; }
        public string IFSC { get; set; }
        public string MICR { get; set; }
        public string BranchContact { get; set; }
    }
}
