//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerModel.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MS_CompReg
    {
        public System.Guid Id { get; set; }
        public Nullable<System.DateTime> FormDate { get; set; }
        public string MachineId { get; set; }
        public string MachineIp { get; set; }
        public string CompanyName { get; set; }
        public string CompanyDomain { get; set; }
        public string CompanyAddress { get; set; }
        public Nullable<int> MS_Country_Id { get; set; }
        public Nullable<int> MS_State_Id { get; set; }
        public Nullable<int> MS_City_Id { get; set; }
        public string Pincode { get; set; }
        public string PFNo { get; set; }
        public string TANNo { get; set; }
        public string PANNo { get; set; }
        public string ESINo { get; set; }
        public string LINNo { get; set; }
        public string GSTNo { get; set; }
        public Nullable<System.DateTime> FinancialYearFrom { get; set; }
        public Nullable<System.DateTime> FinancialYearTo { get; set; }
        public string RegCertNo { get; set; }
        public Nullable<int> IndustryType_Id { get; set; }
        public string Website { get; set; }
        public Nullable<int> Timezone_Id { get; set; }
        public string ReportingCnt { get; set; }
        public string ReportingCntMail { get; set; }
        public string ReportingCntDesg { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
