//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerModel.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MS_Holiday
    {
        public int Id { get; set; }
        public string MachineId { get; set; }
        public string MachineIp { get; set; }
        public Nullable<System.Guid> CompId { get; set; }
        public string HolidayName { get; set; }
        public System.DateTime HolidayOn { get; set; }
        public Nullable<bool> IsOptional { get; set; }
        public int HolidayForContryId { get; set; }
        public Nullable<int> HolidayForStateId { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
