//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerModel.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MS_LN
    {
        public int Id { get; set; }
        public Nullable<System.Guid> CompId { get; set; }
        public string LNTypeName { get; set; }
        public Nullable<decimal> InterestRate { get; set; }
        public Nullable<bool> IsMaxAmtManual { get; set; }
        public Nullable<decimal> MaxAmount { get; set; }
        public Nullable<int> MS_SLHead_Id { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public Nullable<decimal> TenureMonths { get; set; }
        public Nullable<bool> AllowPartialPay { get; set; }
    }
}
