//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerModel.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MS_Leave
    {
        public int Id { get; set; }
        public Nullable<System.Guid> CompId { get; set; }
        public string LeaveName { get; set; }
        public string LeaveCode { get; set; }
        public Nullable<int> LeaveType { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<int> EffectiveAfterOnTypes { get; set; }
        public Nullable<int> CarryForward { get; set; }
        public string ApplicableFor { get; set; }
        public Nullable<int> MS_Branch_Id { get; set; }
        public Nullable<int> DurationAllowed { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
