//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerModel.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MS_Payroll_AdjustType
    {
        public int Id { get; set; }
        public Nullable<System.Guid> CompId { get; set; }
        public bool IsEarningHead { get; set; }
        public string AdjustmentType { get; set; }
        public bool IsRuleBased { get; set; }
        public Nullable<decimal> PercentageAmt { get; set; }
        public Nullable<int> MS_SLHeads_Id { get; set; }
    }
}
