//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerModel.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MS_Reim_Types
    {
        public int Id { get; set; }
        public Nullable<System.Guid> CompId { get; set; }
        public string ReimbursementType { get; set; }
        public Nullable<decimal> MonthlyLimit { get; set; }
        public string Frequency { get; set; }
        public Nullable<bool> IsDesignationSpecific { get; set; }
        public Nullable<int> MS_Designation_Id { get; set; }
    }
}
