//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerModel.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MS_Shift
    {
        public int Id { get; set; }
        public Nullable<System.Guid> CompId { get; set; }
        public Nullable<int> MS_Branch_Id { get; set; }
        public string ShiftName { get; set; }
        public string ShiftCode { get; set; }
        public string ShiftShortName { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public decimal TotalHrs { get; set; }
        public string WeeklyOffDay { get; set; }
        public Nullable<bool> IsShiftAllowance { get; set; }
        public Nullable<decimal> ShiftAllowanceAmtPerDay { get; set; }
        public Nullable<bool> IsOTApplicable { get; set; }
        public Nullable<System.TimeSpan> OTApplicableAfterEndTime { get; set; }
        public Nullable<decimal> OTAmtPerHrs { get; set; }
        public Nullable<System.Guid> EMP_Info_Id { get; set; }
        public Nullable<bool> IsLateMarkApplicable { get; set; }
        public Nullable<System.TimeSpan> LateMarkAfterOn { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
