//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerModel.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MS_SLHeads
    {
        public int Id { get; set; }
        public Nullable<System.Guid> CompId { get; set; }
        public string SalaryHeadName { get; set; }
        public string ShortSalaryHeadName { get; set; }
        public bool IsEarningComponent { get; set; }
        public Nullable<bool> IsFixedComponent { get; set; }
        public Nullable<bool> IsTaxableComponent { get; set; }
        public Nullable<bool> IsShowInSalarySlip { get; set; }
        public Nullable<int> SalaryHeadOrder { get; set; }
        public Nullable<int> MS_SLHeads_Id { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
