//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerModel.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MS_Training
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> FormDate { get; set; }
        public string MachineId { get; set; }
        public string MachineIp { get; set; }
        public Nullable<System.Guid> CompId { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public string TrainingName { get; set; }
        public string TrainingShortName { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsTrainingMandatory { get; set; }
        public Nullable<int> MS_Designation_Id { get; set; }
    }
}
