//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerModel.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PR_EMP_SL
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> FormDate { get; set; }
        public Nullable<System.Guid> CompId { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<int> PR_CRT_Id { get; set; }
        public Nullable<System.Guid> EMP_Info_Id { get; set; }
        public Nullable<System.DateTime> PayrollCreationDt { get; set; }
        public Nullable<int> MS_SLHeads_Id { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
