//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerModel.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PR_EMP_SL_Adjustment
    {
        public System.Guid Id { get; set; }
        public Nullable<System.DateTime> FormDate { get; set; }
        public Nullable<System.Guid> CompId { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public System.Guid EMP_Info_Id { get; set; }
        public System.DateTime PayrollMonthYear { get; set; }
        public decimal Amount { get; set; }
        public int MS_Payroll_AdjstType_Id { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
    }
}
