//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerModel.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PR_Reimbursement
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> FormDate { get; set; }
        public string MachineId { get; set; }
        public string MachineIp { get; set; }
        public Nullable<System.Guid> CompId { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> PayrollCreationDt { get; set; }
        public Nullable<System.Guid> Reim_Claims_Id { get; set; }
        public Nullable<System.Guid> EMP_Info_Id { get; set; }
        public Nullable<int> EMP_Info_MSBranchId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> SGST { get; set; }
        public Nullable<decimal> NetPay { get; set; }
        public string PayrollStatus { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> IsAmmend { get; set; }
        public Nullable<System.DateTime> AmmendDate { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
