//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerModel.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Req_JbVacancy
    {
        public System.Guid Id { get; set; }
        public Nullable<System.DateTime> FormDate { get; set; }
        public string MachineId { get; set; }
        public string MachineIp { get; set; }
        public Nullable<System.Guid> CompId { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<int> MS_Designation_Id { get; set; }
        public Nullable<int> MS_Branch_Id { get; set; }
        public Nullable<System.Guid> HiringManager_Id { get; set; }
        public Nullable<int> NosOfPosition { get; set; }
        public string JobDesc { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
