//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerModel.SqlAccess.Payroll {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServerModel.SqlAccess.Payroll.Sql", typeof(Sql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///---- CalculatePayrollByMonth.Sql
        ///
        ////*
        ///DECLARE @Year INT = 2025;  -- Change the year as needed
        ///DECLARE @Month INT = 1;    -- Change the month number (1-12)
        ///DECLARE @BranchId INT = 2002;
        ///*/
        ///
        ///DECLARE @monthStartDate DATE = DATEFROMPARTS(@Year, @Month, 1);
        ///DECLARE @monthEndDate DATE = EOMONTH(@monthStartDate);
        ///
        ///-- Employee Punch In/Out days
        ///WITH PunchDays AS (
        ///    SELECT DISTINCT
        ///        EMP_Info_Id,
        ///        CAST(PunchDate AS DATE) AS WorkDate
        ///    FROM EMP_Punch
        ///    WHERE Status IN (&apos;In&apos;, &apos;Out [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetCalculatedPayrollDetailsByBranch {
            get {
                return ResourceManager.GetString("GetCalculatedPayrollDetailsByBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ////*
        ///DECLARE @Year INT = 2025;
        ///DECLARE @Month INT = 7;
        ///DECLARE @BranchId INT = 5004;
        ///DECLARE @CompId UNIQUEIDENTIFIER = &apos;c225a53f-9ecb-4b9a-88dc-eaef6115c2a4&apos;
        ///
        ///*/
        ///
        ///DECLARE @monthStartDate DATE = DATEFROMPARTS(@Year, @Month, 1);
        ///DECLARE @monthEndDate DATE = EOMONTH(@monthStartDate);
        ///
        ///
        ///-- Get first punch per day (used to simulate &apos;In&apos; punch)
        ///WITH FirstPunchPerDay AS (
        ///    SELECT 
        ///        EMP_Info_Id,
        ///        CAST(PunchDate AS DATE) AS WorkDate,
        ///        MIN(CAST(PunchTime AS TIME)) AS FirstPun [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetCalculatedPayrollDetailsByBranch_ByShiftAllowance {
            get {
                return ResourceManager.GetString("GetCalculatedPayrollDetailsByBranch_ByShiftAllowance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///----GetCalculatedSalaryAdjustmentByAdjustmentIdByEmployees.Sql
        ///
        ///--DECLARE    @EmpIds NVARCHAR(MAX) = &apos;C7716840-5EEE-4EC7-8E10-2AAF274252AD,5DE2FE64-4D6B-4E75-BA75-B43A143BC4BD&apos;;
        ///--DECLARE    @AdjustmentTypeId INT = 1;
        ///
        ///BEGIN
        ///    SET NOCOUNT ON;
        ///
        ///    -- Split EmpIds string into table
        ///    ;WITH EmpList AS (
        ///        SELECT TRIM(value) AS EMP_Info_Id 
        ///        FROM STRING_SPLIT(@EmpIds, &apos;,&apos;)
        ///    )
        ///    SELECT 
        ///        e.EMP_Info_Id,
        ///        emp.FullName,
        ///        adj.AdjustmentType,
        ///        ad [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetCalculatedSalaryAdjustmentByAdjustmentIdByEmployees {
            get {
                return ResourceManager.GetString("GetCalculatedSalaryAdjustmentByAdjustmentIdByEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///---GetEmployeeReimbursementsByBranchAndMonth.Sql
        ///
        ///
        ///
        ///--DECLARE @BranchId INT  = 5004;
        ///--DECLARE @Month INT = 08;
        ///--DECLARE @Year INT= 2025;
        ///--DECLARE @CompId UNIQUEIDENTIFIER = &apos;C225A53F-9ECB-4B9A-88DC-EAEF6115C2A4&apos;;
        ///
        ///SELECT DISTINCT
        ///	rc.CompId,
        ///    rc.Id AS &apos;Reim_Claims_Id&apos;,
        ///    rc.EMP_Info_Id,
        ///	emp.MS_Branch_Id AS &apos;EMP_Info_MSBranchId&apos;,
        ///	emp.FullName,
        ///    rc.ClaimDate,
        ///	rc.CGST,
        ///	rc.SGST,
        ///    rc.Amount,
        ///	rembType.ReimbursementType,
        ///	rc.ApprovedDate,
        ///    ra.Approver_Emp_Id,
        ///	empApp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetEmployeeReimbursementsByBranchAndMonth {
            get {
                return ResourceManager.GetString("GetEmployeeReimbursementsByBranchAndMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///--- GetEmployeeSalaryHeadsDetails.Sql
        ///
        ///--DECLARE @Year INT = 2025;  -- Change the year as needed
        ///--DECLARE @Month INT = 1;    -- Change the month number (1-12)
        ///--DECLARE @EmpId UNIQUEIDENTIFIER = &apos;566E3EC9-41E2-4EB5-A33A-FF92BFBE2CBE&apos;
        ///
        ///DECLARE @monthStartDate DATE = DATEFROMPARTS(@Year, @Month, 1);
        ///
        ///-- Base Salary Heads
        ///SELECT 
        ///    es.Id,
        ///    es.FormDate,
        ///    es.CompId,
        ///    es.CreatedBy,
        ///    es.EMP_Info_Id,
        ///    es.MS_SLHeads_Id,
        ///    slHead.IsEarningComponent,
        ///    slHead.IsShowInSalarySlip [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetEmployeeSalaryHeadsDetails {
            get {
                return ResourceManager.GetString("GetEmployeeSalaryHeadsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///--- GetEmployeeSalarySlipByMonthAndId.Sql
        ///
        ///--DECLARE @Year INT = 2025;  -- Change the year as needed
        ///--DECLARE @Month INT = 1;    -- Change the month number (1-12)
        ///--DECLARE @EmpId UNIQUEIDENTIFIER = &apos;566E3EC9-41E2-4EB5-A33A-FF92BFBE2CBE&apos;
        ///
        ///SELECT payrollEmpSL.Id
        ///      ,payrollEmpSL.FormDate
        ///      ,payrollEmpSL.CompId
        ///      ,payrollEmpSL.CreatedBy
        ///      ,payrollEmpSL.PR_CRT_Id
        ///      ,payrollEmpSL.EMP_Info_Id
        ///      ,payrollEmpSL.PayrollCreationDt
        ///      ,payrollEmpSL.MS_SLHeads_Id
        ///	  ,slHead.Is [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetEmployeeSalarySlipByMonthAndId {
            get {
                return ResourceManager.GetString("GetEmployeeSalarySlipByMonthAndId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///---- Sql.GetEmpPayrollByBranchMonth
        ///
        ////*
        ///DECLARE @Year INT = 2025;  
        ///DECLARE @Month INT = 1;    
        ///DECLARE @BranchId INT = 2002;
        ///DECLARE @empId UNIQUEIDENTIFIER = &apos;2916952C-8B28-41F4-8022-6783BACDA7F5&apos;
        ///
        ///*/
        ///
        ///DECLARE @CompId UNIQUEIDENTIFIER = (SELECT TOP 1 CompId FROM EMP_Info WHERE Id = @empId);
        ///DECLARE @monthStartDate DATE = DATEFROMPARTS(@Year, @Month, 1);
        ///DECLARE @monthEndDate DATE = EOMONTH(@monthStartDate);
        ///
        ///-- Get dynamic salary heads
        ///DECLARE @cols NVARCHAR(MAX), @sql NVARCHAR(MAX);
        ///
        ///S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetEmpPayrollByBranchMonth {
            get {
                return ResourceManager.GetString("GetEmpPayrollByBranchMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///---GetSalaryAdjustmentEmployeesByCompId.sql
        ///
        ////*
        ///DECLARE @compId UNIQUEIDENTIFIER = &apos;C225A53F-9ECB-4B9A-88DC-EAEF6115C2A4&apos;
        ///**/
        ///
        ///SELECT 
        ///	FORMAT(sladj.PayrollMonthYear, &apos;yyyy-MM&apos;) AS PayrollMonthYear   -- 👈 Month-Year only
        ///	,sladj.Description
        ///	--,sladj.Amount
        ///	,sladj.MS_Payroll_AdjstType_Id
        ///	,adj.AdjustmentType
        ///	,adj.IsEarningHead
        ///	,sladj.Status
        ///	,SUM(sladj.Amount) AS TotalAmount  -- ✅ total per month
        ///	FROM PR_EMP_SL_Adjustment AS sladj
        ///		INNER JOIN EMP_Info AS emp ON emp.Id = sladj.EMP_Inf [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetSalaryAdjustmentEmployeesByCompId {
            get {
                return ResourceManager.GetString("GetSalaryAdjustmentEmployeesByCompId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///----GetSalaryAdjustmentsByPayrollMonthYear.Sql
        ///
        ///--select * from PR_EMP_SL_Adjustment
        ///
        ////*
        ///DECLARE @date DATE = &apos;2025-09-29&apos;;
        ///*/
        ///
        ///SELECT 
        ///			 sladj.Id
        ///			,sladj.FormDate
        ///			,sladj.CompId
        ///			,sladj.EMP_Info_Id
        ///			,emp.FullName
        ///			,sladj.PayrollMonthYear
        ///			,sladj.Amount
        ///			,sladj.MS_Payroll_AdjstType_Id
        ///			,adj.AdjustmentType
        ///			,adj.IsRuleBased
        ///			,CASE 
        ///				WHEN adj.IsRuleBased = 1 THEN 
        ///				    CAST(adj.PercentageAmt AS VARCHAR(10)) + &apos; % Of &apos; + head.SalaryHeadName
        ///				ELSE 
        ///				  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetSalaryAdjustmentsByPayrollMonthYear {
            get {
                return ResourceManager.GetString("GetSalaryAdjustmentsByPayrollMonthYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///----- UpsertEmpSalaryAdjustment.Sql
        ///
        ///-- MERGE query
        ///MERGE PR_EMP_SL_Adjustment AS target
        ///USING @Adjustments AS source
        ///ON  MONTH(target.PayrollMonthYear) = MONTH(source.PayrollMonthYear)
        ///    AND YEAR(target.PayrollMonthYear) = YEAR(source.PayrollMonthYear)
        ///	AND target.EMP_Info_Id = source.EMP_Info_Id
        ///	AND target.MS_Payroll_AdjstType_Id = source.MS_Payroll_AdjstType_Id
        ///WHEN MATCHED THEN
        ///    UPDATE SET 
        ///        Amount = source.Amount,
        ///        MS_Payroll_AdjstType_Id = source.MS_Payroll_AdjstType_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpsertEmpSalaryAdjustment {
            get {
                return ResourceManager.GetString("UpsertEmpSalaryAdjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///----- UpsertPayrollCreation.Sql
        ///
        ////*
        ///DECLARE @json1 nvarchar(max) = 
        ///&apos;[
        ///	{
        ///		&quot;Id&quot;: 0,
        ///		&quot;FormDate&quot;: &quot;2023-01-25 23:33:32.017&quot;,
        ///		&quot;MachineId&quot;: &quot;&quot;,
        ///		&quot;MachineIp&quot;: &quot;&quot;,
        ///		&quot;CompId&quot;: &quot;00000000-0000-0000-0000-000000000000&quot;,
        ///		&quot;CreatedBy&quot;: &quot;00000000-0000-0000-0000-000000000000&quot;,
        ///		&quot;PayrollCreationDt&quot;: &quot;2025-01-25 23:33:32.017&quot;,
        ///		&quot;EMP_Info_Id&quot;: &quot;566E3EC9-41E2-4EB5-A33A-FF92BFBE2CBE&quot;,
        ///		&quot;EMP_Info_MSBranchId&quot;: 2002,
        ///		&quot;TotalPaidDays&quot;: 15,
        ///		&quot;TotalEarning&quot;: 7750.0000000000,
        ///		&quot;TotalDeduction&quot;: 1966.6 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpsertPayrollCreation {
            get {
                return ResourceManager.GetString("UpsertPayrollCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///----- UpsertPayrollReimbursements.Sql
        ///
        ////*
        ///DECLARE @json1 nvarchar(max) = 
        ///&apos;[
        ///	{
        ///		&quot;Id&quot;: 0,
        ///		&quot;FormDate&quot;: &quot;2023-01-25 23:33:32.017&quot;,
        ///		&quot;MachineId&quot;: &quot;&quot;,
        ///		&quot;MachineIp&quot;: &quot;&quot;,
        ///		&quot;CompId&quot;: &quot;00000000-0000-0000-0000-000000000000&quot;,
        ///		&quot;CreatedBy&quot;: &quot;00000000-0000-0000-0000-000000000000&quot;,
        ///		&quot;PayrollCreationDt&quot;: &quot;2025-01-25 23:33:32.017&quot;,
        ///		&quot;Reim_Claims_Id&quot;: &quot;00000000-0000-0000-0000-000000000000&quot;,
        ///		&quot;EMP_Info_Id&quot;: &quot;566E3EC9-41E2-4EB5-A33A-FF92BFBE2CBE&quot;,
        ///		&quot;EMP_Info_MSBranchId&quot;: 2002,
        ///		&quot;Amount&quot;: 15,
        ///		 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpsertPayrollReimbursements {
            get {
                return ResourceManager.GetString("UpsertPayrollReimbursements", resourceCulture);
            }
        }
    }
}
