//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerModel.SqlAccess.Recruitment {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServerModel.SqlAccess.Recruitment.Sql", typeof(Sql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///---Sql.GetCandidateDetailsForGenerateDocById
        ///
        ////*
        ///DECLARE @compId UNIQUEIDENTIFIER = &apos;00000000-0000-0000-0000-000000000000&apos;
        ///DECLARE @candidateId  UNIQUEIDENTIFIER = &apos;949A5F1A-8E89-4DB9-AE3C-FBD8996D3B9D&apos;
        ///
        ///*/
        ///
        ///SELECT 
        ///	 genDoc.Id
        ///	,candDetail.Id AS &apos;Req_JbForm_Id&apos;
        ///	,comp.CompanyName
        ///	,comp.CompanyAddress
        ///	,city.CityName AS &apos;CompCity&apos;
        ///	,state.StateName AS &apos;CompState&apos;
        ///	,country.CountryName AS &apos;CompCountry&apos;
        ///	,comp.Pincode
        ///	,candDetail.FullName AS &apos;CandidateFullName&apos;
        ///	,&apos;&apos; AS &apos;CandidateAddress&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetCandidateDetailsForGenerateDocById {
            get {
                return ResourceManager.GetString("GetCandidateDetailsForGenerateDocById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///---Sql.GetConfirmedCandidatesByCompId
        ///
        ////*
        ///DECLARE @status NVARCHAR(50) = &apos;Confirmed&apos;
        ///DECLARE @compId UNIQUEIDENTIFIER =  &apos;00000000-0000-0000-0000-000000000000&apos;
        ///*/
        ///
        ///SELECT 
        ///		 cand.Id
        ///		,cand.CompId
        ///		,cand.CTC
        ///		,cand.Status
        ///		,cand.DateOfJoining
        ///		,cand.DocExperiesOn
        ///		,candDetail.FullName
        ///		,cand.Req_JbForm_Id
        ///		,candDetail.Email
        ///		,candDetail.ContactNo
        ///		,brn.BranchName
        ///		,desg.DesignationName
        ///		,hiremng.FullName AS &apos;ReportingManager&apos;
        ///		,intSch.Id AS &apos;InterviewScheduledId&apos;
        ///		,intS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetConfirmedCandidatesByCompId {
            get {
                return ResourceManager.GetString("GetConfirmedCandidatesByCompId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///---Sql.GetDocGeneratedCandidatesByCompId.sql.sql
        ///
        ////*
        ///DECLARE @compId UNIQUEIDENTIFIER = &apos;00000000-0000-0000-0000-000000000000&apos;
        ///
        ///*/
        ///
        ///SELECT 
        ///		 empGenDoc.Id
        ///		,empGenDoc.Req_JbForm_Id
        ///		,cand.FullName
        ///		,empGenDoc.Status
        ///		,empGenDoc.DocCreatedOn
        ///		,empGenDoc.DateOfJoining
        ///		,empGenDoc.DocExperiesOn
        ///		,empGenDoc.MS_Doc_Id
        ///	FROM EMP_GenDocs AS empGenDoc
        ///		 INNER JOIN Req_JbForm AS cand ON cand.Id = empGenDoc.Req_JbForm_Id
        ///				AND cand.Active = 1
        ///		WHERE empGenDoc.Status NOT IN (&apos;Confirmed [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetDocGeneratedCandidatesByCompId {
            get {
                return ResourceManager.GetString("GetDocGeneratedCandidatesByCompId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ////*
        ///DECLARE @candidateId UNIQUEIDENTIFIER=  &apos;85264BC4-DF2A-45DA-ACEA-66260B3421FE&apos;
        ///DECLARE @docId INT=  1
        ///*/
        ///
        ///SELECT 
        ///	 EMP_OfferSL.Id
        ///	,EMP_OfferSL.CompId
        ///	,EMP_OfferSL.MS_SLHeads_Id
        ///	,MS_SLHeads.IsEarningComponent
        ///	,MS_SLHeads.SalaryHeadName
        ///	,EMP_OfferSL.Amount AS &apos;AnnualAmount&apos;
        ///	FROM EMP_OfferSL
        ///		INNER JOIN MS_SLHeads ON MS_SLHeads.Id = EMP_OfferSL.MS_SLHeads_Id
        ///		WHERE Req_JbForm_Id = @candidateId
        ///			AND EMP_GenDocs_Id = @docId
        ///			AND IsAmmend = 0
        ///
        ///
        ///
        ///.
        /// </summary>
        internal static string GetEmpOfferSalaryByDocId {
            get {
                return ResourceManager.GetString("GetEmpOfferSalaryByDocId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///---Sql.GetGeneratedDocumentsByCompId.sql
        ///
        ////*
        ///DECLARE @docId INT = 1
        ///*/
        ///
        ///;WITH LatestFeedback AS (
        ///    SELECT 
        ///        fed.*,
        ///        ROW_NUMBER() OVER (PARTITION BY fed.Req_InterviewSch_Id ORDER BY fed.FormDate DESC) AS rn
        ///    FROM Req_InterviewFedbck AS fed
        ///)
        ///SELECT 
        ///     empGenDoc.Id
        ///	,empGenDoc.CompId
        ///    ,empGenDoc.Status
        ///    ,empGenDoc.CTC
        ///    ,empGenDoc.DateOfJoining
        ///    ,empGenDoc.MS_Doc_Id
        ///    ,doc.DocName
        ///    ,empGenDoc.DocPath
        ///    ,cand.FullName
        ///    ,cand.Email
        ///    ,cand.C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetGeneratedDocById {
            get {
                return ResourceManager.GetString("GetGeneratedDocById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///---Sql.GetGeneratedDocumentsByCompId.sql
        ///
        ////*
        ///DECLARE @compId UNIQUEIDENTIFIER = &apos;00000000-0000-0000-0000-000000000000&apos;
        ///
        ///*/
        ///
        ///;WITH LatestFeedback AS (
        ///    SELECT 
        ///        fed.*,
        ///        ROW_NUMBER() OVER (PARTITION BY fed.Req_InterviewSch_Id ORDER BY fed.FormDate DESC) AS rn
        ///    FROM Req_InterviewFedbck AS fed
        ///)
        ///SELECT 
        ///     empGenDoc.Id
        ///	,empGenDoc.CompId
        ///    ,empGenDoc.Status
        ///    ,empGenDoc.CTC
        ///    ,empGenDoc.DateOfJoining
        ///    ,empGenDoc.MS_Doc_Id
        ///    ,doc.DocName
        ///    ,empGenDoc.DocP [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetGeneratedDocumentsByCompId {
            get {
                return ResourceManager.GetString("GetGeneratedDocumentsByCompId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///----Sql.GetInterviewFeedbacksByCompIdAndRating
        ////*
        ///DECLARE @interviewRateId INT = 5;
        ///DECLARE @compId UNIQUEIDENTIFIER = &apos;00000000-0000-0000-0000-000000000000&apos;
        ///
        ///*/
        ///
        ///select 
        ///	intFeedbck.Id,
        ///	intFeedbck.CompId,
        ///	intFeedbck.Req_InterviewSch_Id,
        ///	intFeedbck.EMP_Info_Id AS &apos;FeedBackGivenEmpId&apos;,
        ///	empFeedBackGiven.FullName AS &apos;FeedBackGivenEmpName&apos;,
        ///	intSch.InterviewDateTime,
        ///	intSch.Comments AS &apos;InterviewerComment&apos;,
        ///	intSch.Method,
        ///	intSch.InterviewStatus,
        ///	intSch.EMP_Info_Id AS &apos;InterviewerId&apos;,        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetInterviewFeedbacksByCompIdAndRating {
            get {
                return ResourceManager.GetString("GetInterviewFeedbacksByCompIdAndRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///---Sql.GetScheduleInterviewsByCompId
        ///
        ////*
        ///DECLARE @compId UNIQUEIDENTIFIER = &apos;00000000-0000-0000-0000-000000000000&apos;
        ///DECLARE @InterviewStatus INT;
        ///
        ///*/
        ///
        ///SELECT 
        ///	intSch.Id,
        ///	intSch.FormDate,
        ///	intSch.Req_JbVacancy_Id,
        ///	jobVacancy.HiringManager_Id,
        ///	hiringMngr.FullName AS &apos;HiringManagerName&apos;,
        ///	jobVacancy.MS_Designation_Id,
        ///	desg.DesignationName,
        ///	intSch.Req_JbForm_Id,
        ///	jobForm.FullName,
        ///	jobForm.Email,
        ///	jobForm.ContactNo,
        ///	jobForm.YearOfExp,
        ///	jobForm.Resume,
        ///	intSch.InterviewDateTime,
        ///	i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetScheduleInterviewsByCompId {
            get {
                return ResourceManager.GetString("GetScheduleInterviewsByCompId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///---Sql.UpdateGeneratedDocStatusById
        ///
        ////*
        ///DECLARE @status NVARCHAR(50) = &apos;Confirmed&apos;;
        ///DECLARE @docId INT = 77;
        ///*/
        ///
        ///DECLARE @Success BIT = 0;
        ///
        ///Update EMP_GenDocs
        ///	SET Status = @status
        ///		WHERE Id = @docId
        ///			AND Ammend = 0
        ///			AND Status IN (&apos;NotConfirmed&apos;)
        ///
        ///IF @@ROWCOUNT &gt; 0
        ///    SET @Success = 1;  -- TRUE
        ///ELSE
        ///    SET @Success = 0;  -- FALSE
        ///
        ///SELECT CAST(@Success AS BIT) AS IsSuccessful;.
        /// </summary>
        internal static string UpdateGeneratedDocStatusById {
            get {
                return ResourceManager.GetString("UpdateGeneratedDocStatusById", resourceCulture);
            }
        }
    }
}
