//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerModel.SqlAccess.EmployeeSetup.PersonalInfo.Sql {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServerModel.SqlAccess.EmployeeSetup.PersonalInfo.Sql.Sql", typeof(Sql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ////*
        ///
        ///DECLARE @employeeId UNIQUEIDENTIFIER = &apos;FAC57D97-52DC-4325-9A30-5671CD8FA131&apos;
        ///
        ///*/
        ///
        ///
        ///SELECT depHead.Id, depHead.FullName
        ///	FROM EMP_Info AS emp
        ///		LEFT JOIN MS_Dept AS dept ON dept.Id = emp.MS_Dept_Id
        ///		LEFT JOIN EMP_Info AS depHead ON depHead.Id = dept.DepartmentLead_Id
        ///	WHERE emp.Id = @employeeId
        ///		AND emp.IsActive = 1.
        /// </summary>
        internal static string GetEmployeeApproverByEmpId {
            get {
                return ResourceManager.GetString("GetEmployeeApproverByEmpId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///---SQL.GetEmployeeDetailByEmailAddress
        ////*
        ///DEClARE @emailAddress NVARCHAR(MAX) = &apos;abc@gmail.com&apos;;
        ///
        ///*/
        ///SELECT 
        ///		 emp.Id
        ///		,emp.CompId
        ///		,emp.FullName
        ///		,empPersonal.Email
        ///		,compPlan.ActiveFrom
        ///		,compPlan.ActiveTo
        ///			FROM EMP_PersonalInfo AS empPersonal
        ///				INNER JOIN EMP_Info AS emp ON emp.Id = empPersonal.EMP_Info_Id
        ///				INNER JOIN MS_CompReg AS comp ON comp.Id = empPersonal.CompId
        ///				LEFT JOIN MS_CompPlan AS compPlan ON compPlan.CompId = comp.Id
        ///					AND compPlan.Active = CAST(1 AS BIT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetEmployeeDetailByEmailAddress {
            get {
                return ResourceManager.GetString("GetEmployeeDetailByEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///
        ///-- UpsertEmployeePersonalInfo
        ///
        ///
        ///DECLARE @id uniqueidentifier = &apos;2E2605ED-A9B7-4600-9BDC-6CF3F656D1FB&apos;
        ///DECLARE @formdate DATE = &apos;2023-04-15&apos;
        ///DECLARE @machineIp nvarchar(50) = &apos;1.1.1.1&apos;
        ///DECLARE @machineId nvarchar(50) = &apos;Machine&apos;
        ///DECLARE @compId uniqueidentifier = &apos;00000000-0000-0000-0000-000000000000&apos;
        ///DECLARE @createdby uniqueidentifier = &apos;00000000-0000-0000-0000-000000000000&apos;
        ///DECLARE @empId uniqueidentifier = &apos;00000000-0000-0000-0000-000000000000&apos;
        ///DECLARE @email nvarchar(max) = &apos;email@gmail. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpsertEmployeePersonalInfo {
            get {
                return ResourceManager.GetString("UpsertEmployeePersonalInfo", resourceCulture);
            }
        }
    }
}
