//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerModel.SqlAccess.EmployeeSetup.BankInfo.Sql {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServerModel.SqlAccess.EmployeeSetup.BankInfo.Sql.Sql", typeof(Sql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///---Sql.GetEmployeeAccountDetailByEmpId
        ////*
        ///DECLARE @EMP_Info_Id uniqueidentifier = &apos;566E3EC9-41E2-4EB5-A33A-FF92BFBE2CBE&apos;
        ///DECLARE @compId uniqueidentifier = &apos;566E3EC9-41E2-4EB5-A33A-FF92BFBE2CBE&apos;
        ///
        ///*/
        ///
        ///
        ///SELECT 
        ///       ISNULL(empAcct.Id, 0) AS Id
        ///      ,empInfo.FormDate
        ///      --,empInfo.MachineId
        ///      --,empInfo.MachineIp
        ///      ,empInfo.CompId
        ///      --,empAcct.CreatedBy
        ///      ,empInfo.Id AS EMP_Info_Id
        ///	  ,empInfo.FullName
        ///      ,empAcct.MS_Bank_Id
        ///	  ,bank.BankName
        ///      ,empAcct.MS_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetEmployeeAccountDetailbyEmpId {
            get {
                return ResourceManager.GetString("GetEmployeeAccountDetailbyEmpId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///---Sql.UpsertEmployeeBank
        ///
        ////*
        ///DECLARE @id INT = 1
        ///DECLARE @formdate DATE = &apos;2023-04-15&apos;
        ///DECLARE @machineIp nvarchar(50) = &apos;1.1.1.1&apos;
        ///DECLARE @machineId nvarchar(50) = &apos;Machine1&apos;
        ///DECLARE @compId uniqueidentifier = &apos;00000000-0000-0000-0000-000000000000&apos;
        ///DECLARE @createdby uniqueidentifier = &apos;00000000-0000-0000-0000-000000000000&apos;
        ///DECLARE @EMP_Info_Id uniqueidentifier = &apos;00000000-0000-0000-0000-000000000000&apos;
        ///DECLARE @MS_Bank_Id INT = 0
        ///DECLARE @MS_Bank_Branch_Id INT = 0
        ///DECLARE @AccountNo NVARCHA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpsertEmployeeBankInfo {
            get {
                return ResourceManager.GetString("UpsertEmployeeBankInfo", resourceCulture);
            }
        }
    }
}
